### ISSUE TITLE
path override breaks done-autorender tests

### ISSUE THREAD

**Issue by Bajix** [canjs/can-stache#125]
The following [test](https://github.com/donejs/autorender/pull/29) fails, but only when ran from testee; a clean browser run will pass:

"development mode: the appState is available as the html viewModel"

Upon inspection, it would seem [this line](https://github.com/canjs/can-stache/blob/master/src/mustache_core.js#L1) breaks things. I'm guessing this some sort of path override, maybe for bundling, that fails to resolve, as done-autorender no longer has `can` as a dependency.

This is maybe an error for StealJS too? This seems like something that should be exclusively handled during bundling, but perhaps a fail safe could be useful?

**Comment by matthewp** [comment]
Which line? the line you linked to points to the first line in the file, a comment 🙃

**Comment by matthewp** [comment]
Oh, you really do mean the comment... wow weird.
