### ISSUE TITLE
renderer functions returned by can-stache should not be observable

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#128]
Related to https://github.com/canjs/can-stache-bindings/issues/100

A renderer function like:

```js
var renderer = stache("{{first}} {{last}}");
```

is observable.  This causes confusion if a renderer function is used within a stache helper.  For example:

```js
stache.registerHelper("fullName", function(options){
  return renderer(options.context);
});
```

If `first` or `last` change, it will re-run the `fullName` helper.  This is because observables read by the renderer can "leak" to an outside compute.

A breaking test might look like:

```js
var first = compute("Justin"),
     last = compute("Meyer");

var renderer = stache("{{first}} {{last}}");

var fullNameFrag = compute(function(){
  return renderer({first: first, last: last});
});

fullNameFrag.on("change", function(){
  QUnit.ok(false);
});

first("Josh");
```

I'm actually pretty confused how this is happening.  Presumably the reading of `first` and `last` happens in a compute already.  What observable read is "leaking" to the `fullNameFrag`?

**Comment by justinbmeyer** [comment]
cc @bmomberger-bitovi @imjoshdean

**Comment by bmomberger-bitovi** [comment]
Are there cases where you would want the renderer to be observable?  I'm guessing you can do it somehow with can-view-live if you need to?

**Comment by matthewp** [comment]
Just to clarify, this should work with this change, correct?

```js
var fragCompute = compute(function(){
  return renderer(map);
});

fragCompute();
fragCompute.bind("change", function(){
  // this was called b/c of map.foo changing, right?
});

map.foo = "bar";
```

**Comment by matthewp** [comment]
nm, I guess you wouldn't really want that anyways.

**Comment by justinbmeyer** [comment]
Yeah, the idea is that a rendered template responds to the observables within it.  

I could see a use case for text-only stache templates that would be observable like:

```
var template = stache.text("<h1>{{verb}} {{subject}}</h1>");

var myText = template( data );

myText //-> compute 

myText() //-> "<h1>....</h1>"

myText.on("change", .... )
```

but that's not a use case we have a strong need to support, so I think this is fine.
