### ISSUE TITLE
Add greater than and less than helper

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-stache#143]
Make a `{{#gt}}` and `{{#lt}}` similar to `{{#eq}}` but for greater than and less than.

**Comment by Sinjhin** [comment]
matthew
maybe we should have a can-stache-helpers like can-stache-converters

justinmeyer
what for?
what would be in / out?

matthew
i don't know
how do we avoid bundling too many helpers in stache?

justinmeyer
people can probably create their own separate helper-packs
can-stache-comparison-helpers

matthew
that's what i was suggesting
you mean grouped by type
i like that too

justinmeyer
yeah, I think we should have a “core” set of helpers
but then people can make their own groupings

**Comment by justinbmeyer** [comment]
@Sinjhin I'm closing this because I'm wary of adding any more helpers to core `can-stache`.  However, I'll happily help you create a `can-stache-compare-helpers` or something with these helpers.

**Comment by andrejewski** [comment]
@justinbmeyer lied, he didn't close this; I will.

![Teamwork!](https://media.giphy.com/media/26h0oQ3erWGYjdSi4/giphy.gif)
