### ISSUE TITLE
More helpful message for unmatched closing tag

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/can-stache#149]
Moved here from https://github.com/canjs/steal-stache/issues/21

I just removed an `{{#if condition}}` tag and forgot to remove the corresponding `{{/if}}` - the error message is not very helpful:

![image](https://cloud.githubusercontent.com/assets/514040/21863317/2a9db8ec-d7fa-11e6-944c-257ac96fcc15.png)

 Is it possible for the parsing engine to warn me in a more meaningful way. This is a rather large template and it was difficult to find manually.

**Comment by phillipskevin** [comment]
This was closed by the PRs for https://github.com/canjs/can-stache/issues/13.
