### ISSUE TITLE
Renderers are interpreted as functions and not properties

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-stache#150]
http://jsbin.com/lehokefihi/edit?js,console,output

If I have a view model like this: 
```javascript
const ParentVM = DefineMap.extend({
  renderer: {
    value: stache('<child-component (childchange)="onChild" />')
  },
  onChild(){
    console.log('child emitted event');
    this.dispatch('parentchange');
  },
});
```
and a template like this: 
```html
{{>renderer}}
```

I **think** what happens is stache thinks the renderer is a function, not a property on the view model so it tries to look up a partial by name, where name='renderer' and fails. 

The solution is to wrap the rederer in an object, and then it works. But shouldn't this method above work as well?

**Comment by justinbmeyer** [comment]
`value` takes a function, and runs it to get the result for the property value.  This means that:

`new ParentVM().renderer //-> frag`

`{{>}}` needs a renderer function.  Try:

```js
var renderer = stache('<child-component (childchange)="onChild" />');

const ParentVM = DefineMap.extend({
  renderer: {
    value: function(){
      return renderer;
    }
  },
  onChild(){
    console.log('child emitted event');
    this.dispatch('parentchange');
  },
});
```

Closing b/c I'm pretty sure this should work.

**Comment by roemhildtg** [comment]
Of course... :disappointed:
