### ISSUE TITLE
can-curl

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#151]
I'd like to start a discussion around `can-stache` 4.0. 

## Goals 

I think the goal of `can-stache` 4.0 should be:

- Called something other than `can-stache`.  This will allow us to put it in ecosystem, making it part of CanJS 3.0.  Eventually it can be moved into core.  
- Making an easier, more JavaScript-like experience.
- Moving to the direction where every module is "self contained". For example, removing helpers.  
- Minimizing the "cost" of loading `can-stache@4.X` along side `can-stache@3.X` by being compatible with `can-stache@3.X`'s dependencies.  This will make it easier to use `4.0` along side `3.0`.

The following are some ideas

## __Variable based__ Proposal

```
<import from="my-helpers" as="helpers"/>
<import from="student-view.curly" as="studentView">
<ul>
   {#for classRoom of viewModel.classRooms}
      <li class={classRoom.type}>
        {#let teacher be classRoom.teacher}           
            <p> Name: {classRoom.name} </p>
            <p> Teacher: {teacher.name}  </p>
            <p> {#if !teacher.hasKeys( classRoom } } No keys {else} Keys {/if}</p>
            <p> {#if viewModel.activeTeacher === teacher } ACTIVE {/if}}</p>
            <p> { helpers.prettyDate( classRoom.startTime ) } </p>
            { studentView( classRoom.students ) }
          {/let}
     </li>
   {/for}
</ul>
```

Notes:

 - The scope is _variable_ based without an implicit context (`.`).  The data passed to the template is always referred to as `viewModel`.
 - The [special](http://canjs.com/doc/can-stache/keys/special.html) reserved words would not use `%`.  They would just be reserved like `arguments`, `scope`, `event`, `element`, 
 - Uses `{}` instead of `{{}}` as delimiter.
 - We would add operators like `===` and `!`. 
 - Functions must be called.
 - The only helpers that exist will be `for`, `let`, `if`, `switch`.
 - Methods are always passed values.  Helpers are still passed computes.
 - `<import>` just imports into the variable scope.  The `viewModel` is the only value in the variable scope.

Pros:

 - This is much more `JS` like.  I think it will be easier for people to pick up, and easier to debug compared to the current `can-stache`.
 - This can be done relatively easily.

Cons:

 - `{}` might not work great with syntax highlighters.  But I think `dash` syntax highlighting might be a good start.

Questions:

 - Should this swallow missing property values?  For example, what if `viewModel.classRooms` is undefined at first?

Names:

- `can-curly`
- `can-curls`
-`can-$tashe` (won't work, but would be fun)

**Comment by matthewp** [comment]
Cool, here are some thoughts:

> The only helpers that exist will be for, let, if, switch.

Do you mean that these will be the only built-in helpers or the only helpers at all, meaning no 3rd party helpers?

> <import> just imports into the variable scope. The viewModel is the only value in the variable scope.

Is the `as` special attribute specific to the `<import>` element or does it exist for any element?

> This is much more JS like. I think it will be easier for people to pick up, and easier to debug compared to the current can-stache.

Why do you think it will be easier to debug? Will it compile to JavaScript?

-----

Pros:

* I think single {} is a good idea to differentiate from stache/handlebars/etc.
* I like that everything is explicitly named in `#for` and `#let`.

Cons:

* It looks like this isn't valid HTML and therefore needs a parser and can't be used in a `<template>` tag.
* I'm not sure if this is a goal or not, but if it is to appeal to fans of JSX I think it's mistaken. I don't think JSX fans want a templating language that is *like JS*, they want JS. Meaning if it's not a JavaScript module, I don't think it will be appealing to those who like that style.

**Comment by justinbmeyer** [comment]
@matthewp 

> Do you mean that these will be the only built-in helpers or the only helpers at all, meaning no 3rd party helpers?

They will be the only built-in helpers .. but these helpers will probably require some parsing rules, so they will be a bit different from other helpers.  I DO want to discourage people from making helpers.  In `JS`, you can't add something like `for()` or `if()` to the language. I like that limitation.  Everything should look like a function except for some of the basic control/flow expressions.

> Is the as special attribute specific to the <import> element or does it exist for any element?

This is probably a mistake.  I'd probably stick with something like the existing bindings to export it into the scope: `<can-import from="my-helpers" {^value}="helpers"/>`.

> Why do you think it will be easier to debug?

It wont compile to JS (not at least in the 1st version).  I should say it will be easier to make _understandable_ development tools.  What I mean by this is that we can provide a view that has a closure lookup just like chrome dev tools.  


> I'm not sure if this is a goal or not, but if it is to appeal to fans of JSX I think it's mistaken. ... Meaning if it's not a JavaScript module, I don't think it will be appealing to those who like that style.

JSX isn't a JavaScript module on its own right?  It still needs to be processed and turned into a template engine.

The goals are those listed above.  However, making something "more appealing" to JSX users would still be useful.  Say someone checks out CanJS as an alternative to React, we don't have to score a victory in template language syntax. We've got a bunch of other demonstrably useful tools. But being 2 points behind is much better than 6 points behind.  

I do think being "more" JS is appealing to JS developers and I don't think there's an _uncanny valley_ here.

**Comment by matthewp** [comment]
> JSX isn't a JavaScript module on its own right? It still needs to be processed and turned into a template engine.

No, it's not a template engine, the `<foo>` parts gets transpiled into function calls `React.createElement(foo)`.

> The goals are those listed above. However, making something "more appealing" to JSX users would still be useful. 

I don't, I think you're mistakenly attributing the popularity of JSX to the fact that it **looks** like JavaScript. Everything I've read from React fans is that they like that fact that the JSX parts are objects that can be manipulated like any other JavaScript object, that you can use normal JavaScript control flow to manipulate a view.  This means that when a new JavaScript feature is added to the language it doesn't also have to be added to the "JSX language". JSX is strictly a superset. In this new language you are proposing it's not a superset of JS

> I do think being "more" JS is appealing to JS developers and I don't think there's an uncanny valley here.

I don't think there's an uncanny valley here, it's another templating language. But I don't think JSX users would find this any more appealing than other templating language.

**Comment by justinbmeyer** [comment]
@matthewp 

> No, it's not a template engine

I considered EJS a template engine and it did the same thing.  I mean't "turned into a module".  

> I don't, I think you're mistakenly attributing the popularity of JSX to the fact that it looks like JavaScript.

I don't think I am.  I think this is probably one of the biggest reasons for its success.  All the other stuff is just nice.

> But I don't think JSX users would find this any more appealing than other templating language.

My experience teaching stache makes me strongly think the opposite.  If you asked a JSX user if they would prefer something like `can-curls` over `can-stache`, 90% would say `can-curls`.

**Comment by justinbmeyer** [comment]
@matthewp to make sure what I've been trying to say is clear ... I'm not trying to make this more appealing to JSX fans than JSX. I'm trying to make it more appealing to JSX fans than `can-stache`.

**Comment by justinbmeyer** [comment]
Related proposal: https://github.com/canjs/canjs/issues/2971

**Comment by matthewp** [comment]
Right, I think you're misattributing what they like about JSX to be about the *look* and not the functionality.

**Comment by matthewp** [comment]
> I considered EJS a template engine and it did the same thing. I meant "turned into a module".

 EJS was the opposite of JSX. It was JS in a templating language, JSX is templating **syntax** in JavaScript.

**Comment by justinbmeyer** [comment]
That's not really the opposite. Any JS was valid JS. We could have assumed that JS was on the outside pretty easily. 

module.exports = function() { %> <div/> <%}

**Comment by justinbmeyer** [comment]
I think that something a more advanced user would come to appreciate. A new person just cares that it's easy to get live bound DOM and doesn't have to lean much.

**Comment by justinbmeyer** [comment]
> Look towards what templating languages have become popular in recent years, Vue for example.

I am.  React is arguably the most popular.  Even Vue allows any [expression](https://vuejs.org/v2/guide/syntax.html#Using-JavaScript-Expressions) within its bindings.  

I'm confused what you are trying to say at the end of the day.  Do you think `can-curly` would be harder for people to learn than `can-stache`?  Are you saying we should instead rebuilt from the ground up (which would make simultaneous use more expensive and the release further away)?  

I can't imagine you would want to shy away from more JS familiarity and syntax in our templates, but it is coming across that way.

**Comment by marshallswain** [comment]
Can we get rid of the hashes for common helpers like

```
<import from="my-helpers" as="helpers"/>
<import from="student-view.curly" as="studentView">
<ul>
   {for classRoom of viewModel.classRooms}
      <li class={classRoom.type}>
        {let teacher be classRoom.teacher}           
            <p> Name: {classRoom.name} </p>
            <p> Teacher: {teacher.name}  </p>
            <p> {if !teacher.hasKeys( classRoom } } No keys {else} Keys {/if}</p>
            <p> {if viewModel.activeTeacher === teacher } ACTIVE {/if}}</p>
            <p> { helpers.prettyDate( classRoom.startTime ) } </p>
            { studentView( classRoom.students ) }
          {/let}
     </li>
   {/for}
</ul>
```

Or does the hash serve as a reminder that it isn't JS, but is JS-like?

**Comment by marshallswain** [comment]
I like what I see so far.

**Comment by DesignByOnyx** [comment]
One nice thing about react is that you can actually write javascript when you need to do really simple stuff in your view. For example, an input and label need to use the same `id/for` respectively - so you declare a variable and use it. You can render lists using real `forEach/map/filter/et al` - which just feels better than `{#each}...{/each}`. You can perform view-specific logic directly in the view without needing to expand the VM with view-specific data. Real ternary operators are a lot easier than `{#if)...{#else}`, real string interpolation is better than a new syntax, the ability to define functions which return a small chunk of your view is much more convenient than a separate partial or external file. There are other use cases where writing a helper or some other code outside the view is just tedious. These are simple little things I'm talking about - only needed by the view - not business logic, no need for testing, just stuff needed to render html. If something is later determined to be "test worthy" or needs to be reused elsewhere, then it's already written in real javascript and it's a matter of simple copy and paste refactoring.

Also, this is strictly an opinion, but I think it would be a huge mistake to try and design 4.x around the ability to work side-by-side with 3.x. 99% of people are going to use one or the other, so we should just make this a requirement so we can focus on building what people need/want vs. building what works with previous versions. `</my-2-cents>`

**Comment by matthewp** [comment]
@justinbmeyer 

> I'm confused what you are trying to say at the end of the day. Do you think can-curly would be harder for people to learn than can-stache? Are you saying we should instead rebuilt from the ground up (which would make simultaneous use more expensive and the release further away)?

> I can't imagine you would want to shy away from more JS familiarity and syntax in our templates, but it is coming across that way.

I don't think JavaScript is a very good language for expressing UI.   If you look at what's happening the JSX world they are debating things like [conditional syntax](https://github.com/facebook/jsx/issues/65#issuecomment-254052500) and are pushing hard for do expression in ES201x because it helps make JS more expressive.  The appeal of JSX/JS for UI is that you can always do things "the hard way" if necessary, and there doesn't need to be a new language feature added to cover everything. So I think that this idea adopts the not so great syntax without bringing in the ability to drop down to JavaScript.

I don't think text/plain is the right constraint to go with for a new templating language in 2017. A new templating language is going to take a couple of years to adopt and will need to be supported for at least a couple of more after that. Given that I'd prefer one of these constraints:

* A language that is parsable by the HTML parser (browser), which means can be included in a `<template>`. This provides the usual benefits of choosing a browser feature.
* A language that transpiles to JavaScript code. Probably just JSX here.

**Comment by justinbmeyer** [comment]
@matthew aren't the last two mutually exclusive? You couldn't put react in a template afaik.

**Comment by justinbmeyer** [comment]
Ryan, making it easy to transition is what canjs is all about. There are apps that last years and people aren't going to want to load another stack.

**Comment by justinbmeyer** [comment]
I think there is a middle ground between expressiveness (we can do condition property reads by default), familiarity (looks like JS) and practical (we can make an improvement in a short period of time, and it fits in well with the stack)

**Comment by justinbmeyer** [comment]
So, I've thought about this a lot and I'm going to try my best to explain why I think `can-curl` would be so useful ... with an analogy.

Picking a framework is like buying a house.  It's a complex decision, and one you are stuck with for a while.

The `view layer` is like the kitchen.  It's the room that people value the most.  

CanJS is like a big house with a shitty kitchen, a great master bedroom, a finished basement, and more.

React is like a house with a professional kitchen, but little else.

`can-curl` is like a $200 paint job that fixes many of the kitchen's worst problems.  With little effort (because we already have the infrastructure for it), we can fix things like:

- It can be hard to tell where properties or methods come from within a template.  
   - For example, `{{something}}` might be anywhere in the scope.  This has been a big problem in `Bitcentive` that works on a very nested structure.  `{myObject.something}`, while longer, makes it easier to know what is happening.
   - `stache` has an implicit context that you access like `{{.}}` or `{{../}}` instead of a variable. 
- Two different "calling things" signatures (Call Expressions vs Helper Expressions).  
- Helper Expressions passes `computes` by default which confuses everyone.
- You have to use `@` to pass a function.  This makes certain view bindings hard to remember.  It's actually not possible to pass a function returned by another function.
- Two different "scopes" (Data scope vs Helper scope)
- Two different ways of looping (`{{#each}}` vs `{{#}}`)
- Two different ways of branching (`{{#if}}` vs `{{#}}`)
- An unnecessary way of calling a subtemplate (`{{>}}`) which can be replaced with just `{template(data)}`.
- A `for/in` loop and the `[]` operator mean we no longer need `%index` and `%key`.
- I think the `%special` can mostly go away.  We'd just need `event`.  
- `let` removes the need for `*variables`.

This coat of paint is cheap and can help sell the house to a lot of people in the short term.  Eventually, we can put in the investment to do a full demolition.

**Comment by phillipskevin** [comment]
Although I think a lot of the benefits listed in the "$200 paint job" analogy are useful and would help new users onboard to writing CanJS, I think that adding a `can-curly` alongside `can-stache` would be really confusing to a lot of people. I don't think that most existing projects would use both in the same project just because of how confusing it would be for new developers to onboard to those projects and context switch between different views that have different template syntaxes.

Would it be possible to achieve the same results the old fashioned way? ie:

* Adding any new features in a 3.x minor releases (`for/in`, `let`, `template()`, etc)
* Update our existing guides to always show the "non-confusing" solution (always show `{{#each todos as todo}}`, etc)
* Deprecating features in 3.x and removing in 4.x

**Comment by justinbmeyer** [comment]
@phillipskevin I think people did transition between `ejs` and `mustache` in the same project.  And then again with `mustache` to `stache`.  I know I've worked on projects with both `ejs` and `stache`.  

While some features could be added, I don't think the most important one would be ... getting rid of the implicit context for variable lookup.

**Comment by matthewp** [comment]
I agree with most of the problems listed above and I'm glad you are thinking of ways to improve things. My qualms are:

1. A $200 coat of paint disincentivizes you from ever doing the full demolition. "We'll fix it later" is something we often say in software development but how often do we actually go back and fix it? Rarely in my experience.
2. There are opportunities to improve templating outside of the syntax. Using `<template>` as an example, going in that direction would mean stuff like `leakScope` could entirely go away as it solves that use case elegantly.
3. Slightly better than can-stache is aiming too low in my opinion. I think we should aim high and build awesome things.

My biggest issue is #1, creating a new templating language is a big investment that means it's going to be the defacto for the next 2-3 years at minimum. Do you really want to be writing this way in 2 or 3 years? I do not.

**Comment by gsmeets** [comment]
I hope you'll at least aim for somewhat of a feature parity between v3 and v4. It's already a hard sell for me here to upgrade all our can components from the 2.2 to the 3.0 syntax. Deprecating v3 in favour of the next hot thing will have crippling effects for those of us running canjs on long-lived highly maintained applications.

**Comment by frank-dspeed** [comment]
Can't we simply build brideges and use any syntax react ejs we export simply the results of any language aka syntax to a canjs frindly one? So we don't even deal with a syntax for our own templating engine with live bindings for example people could easy use react or what ever, knockout does a good job with that

It can't be so hard to get this stuff into our canjs viewModel or is it?

**Comment by matthewp** [comment]
@gsmeets I think you mean the 2.2 -> 2.3 binding syntax. There were no major changes in 3.0 that I'm aware of.  As for your concerns, with 3.0's modularity can-stache can live side-by-side with any other templating languages.

@frank-dspeed check out https://github.com/canjs/react-view-models

**Comment by frank-dspeed** [comment]
http://knockoutjs.com/[http://knockoutjs.com/](url)

**Comment by leoj3n** [comment]
This isn't an RFP or anything, but what about [the kind of stuff that Polymer does](http://stackoverflow.com/questions/22974366/polymer-how-to-loop-and-render-html-to-screen)? They basically us HTML itself as the template language, and just use attributes and custom elements to get things done.

**Comment by matthewp** [comment]
@leoj3n, I'm a fan of that approach. See https://github.com/matthewp/weston for a CanJS template engine that is similar.

**Comment by leoj3n** [comment]
I don't necessarily know the magic behind stache or weston, but I know how they feel, and I had a lot of fun learning Polymer but not so much joy was had trying to understand the current templating language in CanJS or w/e. To be honest it kind of reminded me of the PHP days, trying to shoehorn PHP syntax into HTML using things like Twig which, in the spirit of honestly, slowed me down to the point of failure.

**Comment by justinbmeyer** [comment]
much of this is in CanJS 4 and 5
