### ISSUE TITLE
Make it easy to call the current template as a partial.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#159]
In the file navigation: https://gist.github.com/justinbmeyer/adc9797a8ac1713b9d6d21d33a44e829 you have to register the template as a partial so it can call itself. 

I'd like to fix this.  

Perhaps we can do `{{>*self}}` as we can make the template scope always have a reference to itself.

Maybe `{{>self}}` will work.

I'm a tiny bit wary of `self` because we've wanted to use that for viewModels and other things previously.  Within a template `self` could mean many things.

**Comment by rjgotten** [comment]
Why not `{{> .}}`? It's analogous to `{{.}}` as the current scope.
I think the special case where you'd want the current scope value to be used as the template is a lot less prone to being tripped than using a keyword like `self`.

Alternatively, why not just `{{>}}` ? If it's self-referential, it doesn't need a path or template function reference *at all*.

**Comment by justinbmeyer** [comment]
{{>}} is a good idea

**Comment by Sinjhin** [comment]
Closed with release `3.6.3`
