### ISSUE TITLE
Alias (name) to `each` helper context - P(3) ~12

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#16]
From: https://github.com/canjs/canjs/issues/1735

```mustache
{{#each readings}}
<some-component reading="{.}"/>
{{/each}}
```
Some times I want to wrap it with `<another-component>` and I have to change `{.}` to `{../.}` or even '{../../.}' for double wrap

```mustache
{{#each readings}}
<another-component/>
  <and-another-component/>
   <some-component reading="{../../.}"/>
  </and-another-component/>
</another-component/>
{{/each}}
```
If one could have name for `each` heper context and refere to it by given name, it would be more convinient without need of backtrack paths.

```mustache
{{#each readings "reading"}}
<another-component/>
  <and-another-component/>
    <some-component reading="{reading}"/>
  </and-another-component/>
</another-component/>
{{/each}}
```

emberjs does it using sintax something like like: `{{#each readings as "reading"}}`

**Comment by taai** [comment]
@justinbmeyer I guess this issue can be closed now – it's implemented by pull request #20
