### ISSUE TITLE
Use Observations instead of computes

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#162]
It should be possible to use `can-observation` directly within can-stache and can-view-live where the compute is created here: https://github.com/canjs/can-stache/blob/8fa5969381d8f950a82b162443e7dd8796a61ba4/src/mustache_core.js#L332

This should improve performance by about 10%.

**Comment by justinbmeyer** [comment]
It should eliminate all the following calls:

![canjs_v3_4_1](https://cloud.githubusercontent.com/assets/78602/23556800/7087dc18-fff3-11e6-87d5-cfc68037957e.png)

**Comment by matthewp** [comment]
I still don't understand those profile tools. Where do you get 10% from that? I want to understand how to use those tools better.

**Comment by justinbmeyer** [comment]
If you eliminate those calls, they add up to ~10% of the total execution time.
