### ISSUE TITLE
check if content is already registered before registering it

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#165]
this will prevent some live-reload issues.

basically do:

```js
if( !viewCallbacks.tag("callback") ) {
viewCallbacks.tag("content", function(el, tagData) {
	return tagData.scope;
})
}
```

https://github.com/canjs/can-stache/blob/master/can-stache.js#L26

**Comment by phillipskevin** [comment]
@justinbmeyer this should also prevent these warnings, right?

![image](https://cloud.githubusercontent.com/assets/5851984/23755251/4f272a04-04a5-11e7-993a-8b31f627aa02.png)

**Comment by justinbmeyer** [comment]
yeah, that's why I wanted it :-)

**Comment by cherifGsoul** [comment]
@justinbmeyer ```callback``` param should be ```content```, that's what you mean? so the fix is:
```
if( !viewCallbacks.tag("content") ) {
viewCallbacks.tag("content", function(el, tagData) {
	return tagData.scope;
})
}
```
