### ISSUE TITLE
{{#if @expr}} evaluates the function and checks the returned value

### ISSUE THREAD

**Issue by nlundquist** [canjs/can-stache#172]
When using ```{{#if @func}}``` to render a subtree, the function referenced is called and the return value checked though I expect to just be doing a truthy check to see if the function exists in the scope.

See: http://jsbin.com/mikoqidesa/1/edit?html,console,output

This issue effects can-stache included in CanJS 2.3 and the current 3.5.x release.

**Comment by nlundquist** [comment]
As noted by @phillipskevin even just ```{{@testFunction}}``` ends up running the function

**Comment by christopherjbaker** [comment]
It appears that `{{@testFunction}}` functionality was fixed in v3.0.21 (can.all@3,5,1 is using can-stache v3.0.20). A test for this is will be included with the fix for `{{#if @testFunction}}`.

**Comment by phillipskevin** [comment]
Was it [this change](https://github.com/canjs/can-stache/pull/174/commits/b2f412f5ee3ba03103e16e2da401dc8e751dc669) that fixed `{{ @testFunction }}`? I tried reverting that commit on your `172-at-args-no-execute` branch, but don't get any test failures, so I'm not entirely sure.

**Comment by christopherjbaker** [comment]
Ah! Turns out the behaviour for `{{@func}}` is different when the data is a plain object vs an instance of DefineMap. Interestingly, it is the same regardless for `{{#if @func}}`. I imagine the fix will be basically the same, I just need to track down where it goes.
