### ISSUE TITLE
ViewModel properties using dots don't bind correctly in Stache

### ISSUE THREAD

**Issue by kylegifford** [canjs/can-stache#173]
If you have a ViewModel property that contains a dot (`.`) character, you can not bind to that property in Stache using bracket syntax (this should not work without brackets) (e.g. `{{['property.with.dot']}}`.

Example: 
http://jsbin.com/buteyasena/edit?html,js,output

**Comment by phillipskevin** [comment]
https://github.com/canjs/can-stache/pull/174 added support for:
```
{{ foo["bar.baz"] }}
```

But currently, you cannot use two-way binding to update the property. Meaning this won't work:
```
<input {($value)}="foo['bar.baz']" >
```

And this doesn't work yet at all:
```
{{ ["bar.baz"] }}
```

**Comment by phillipskevin** [comment]
No, I don't think it worked for setting. Also, there are some issues with `can-map` because this was never merged: https://github.com/canjs/can-observation/pull/76. If I recall, we decided to hold off on this until `can-reflect` was in so that we could handle the different cases correctly on Map / DefineMap since they have slightly different behavior (https://canjs.com/doc/can-map.prototype.attr.html#Propertieswithdotsintheirname).

**Comment by bmomberger-bitovi** [comment]
With latest master, `{{ ["bar.baz"] }}` is working.  Still have to check up on the two-way binding.

**Comment by phillipskevin** [comment]
@bmomberger-bitovi this was worked on already by @James0x57, see https://github.com/canjs/can-stache/pull/285.

**Comment by phillipskevin** [comment]
Just needs to get cleaned up and merged.

**Comment by bmomberger-bitovi** [comment]
Checked against `<input {($value)}="foo['bar.baz']" >` in can-stache-bindings as well, since that wasn't covered in the #285 tests.  Works fine, but I recommend setting the can-stache dependency there to be "^3.7.1"

**Comment by phillipskevin** [comment]
@James0x57 added some tests in https://github.com/canjs/can-stache-bindings/pull/290 also. We should have updated the dependency to be `^3.7.1` there, thanks for pointing that out. If you want to put in a PR for that, that would be great.

**Comment by bmomberger-bitovi** [comment]
Done, as https://github.com/canjs/can-stache-bindings/pull/296
