### ISSUE TITLE
Change how dynamic imports are defined

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache#176]
Currently dynamic imports are defined by having a closing tag. This has led to confusion from a lot of users, such as [in this issue](https://github.com/donejs/donejs/issues/887). Instead of having an implicit way to define dynamic imports we should have an explicit way. I think the `lazy` attribute should be used.

```handlebars
<can-import from="my/custom/element" {^is-resolved}="*loaded" lazy />

{{#if *loaded}}
  <my-element/>
{{/if}}
```

Or you could still use the closing tag like before:

```handlebars
<can-import from="my/custom/element" lazy>
  {{#if isResolved}}
    <my-element/>
  {{/if}}
</can-import>
```

**Comment by matthewp** [comment]
The related issue in [can-view-import](https://github.com/canjs/can-view-import/issues/9).

**Comment by matthewp** [comment]
We can probably fix it so that this is detected as static:

```handlebars
<can-import from="my/custom/element"></can-import>
```

And support the normal static form for at least a little while:

```handlebars
<can-import from="my/custom/element">
  {{#if isResolved}}

  {{/if}}
</can-import>
```

**Comment by matthewp** [comment]
Based on some discussion we might want to go with `dynamic` over `lazy` as the attribute.

**Comment by phillipskevin** [comment]
I also posted some thoughts on https://github.com/canjs/can-view-import/issues/9#issuecomment-290765007 based on our discussion.

**Comment by phillipskevin** [comment]
The `can-dynamic-import` tag has been added and @bmomberger-bitovi also fixed converting `<can-import from="my/custom/element"></can-import>` to a static import.
