### ISSUE TITLE
{{#if object[%index]}} doesn’t update when value changes

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache#180]
__Description:__

When the value of `object[%index]` changes, the rendered template doesn’t update.

__Steps to reproduce:__

1. Open http://jsbin.com/leqecog/1/edit?html,js,console,output
2. Click on one of the toggle buttons or checkboxes.

__Expected results:__

The table below would only show the values that are true.

__Actual results:__

The table doesn’t update.

__Additional notes:__

If you click on the checkboxes, an error is shown in the console (`Uncaught TypeError: key.charAt is not a function`). The buttons don’t throw any errors (they just don’t work). 

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 3.0.20
| Browser                    | Chrome & Safari
| Operating system    | macOS

**Comment by christopherjbaker** [comment]
From examining the code and writing a few tests, it seems that DefineList does not create setters for numeric indexes (whereas DefineMap does for the keys it knows about). What I think is happening is that even though `this.flags[index] = X.` changes the value (because javascript), no events are fired, and so no updates are made. Switching out that line for `this.flags.set(index, X);` causes the table to update correctly (though the checkboxes do not. see below).

When I change a checkbox value, I get an error (see below). The checked state changes, but all further interactivity dies; the fixed buttons do nothing, and even changing checkboxes again does not generate errors (though the check state still changes).

```
VM120 can.all.js:1898 Uncaught TypeError: key.charAt is not a function
    at Object.reads (https://unpkg.com/can@3.5.1/dist/global/can.all.js:1898:21)
    at Compute.<anonymous> (https://unpkg.com/can@3.5.1/dist/global/can.all.js:5835:63)
    at Compute.set (https://unpkg.com/can@3.5.1/dist/global/can.all.js:2179:31)
    at compute (https://unpkg.com/can@3.5.1/dist/global/can.all.js:2322:48)
    at Function.updateParent (https://unpkg.com/can@3.5.1/dist/global/can.all.js:6933:25)
    at Compute.handler.(anonymous function) (https://unpkg.com/can@3.5.1/dist/global/can.all.js:2305:25)
    at Object.flush (https://unpkg.com/can@3.5.1/dist/global/can.all.js:1239:37)
    at Object.stop (https://unpkg.com/can@3.5.1/dist/global/can.all.js:1215:30)
    at Compute.dispatch (https://unpkg.com/can@3.5.1/dist/global/can.all.js:1291:34)
    at updateOnChange (https://unpkg.com/can@3.5.1/dist/global/can.all.js:2020:31)
﻿```

**Comment by christopherjbaker** [comment]
Update: using syntax like `<input type="checkbox" {($checked)}="flags.0" />` fixes the issue. I will have to dig a little to find where the differences in handling in code, but that should be fixable.

**Comment by christopherjbaker** [comment]
I think I have a related use case, though using dot notation does not make a difference. http://jsbin.com/fuwowuf/edit?js,console,output

**Comment by phillipskevin** [comment]
A lot of this code is changing with the work @justinbmeyer is doing for `can-reflect`, so we're going to wait for that to land before fixing this issue. That is why I moved it into the Can 3.6.0 Epic.

**Comment by Alfredo-Delgado** [comment]
Will address here: https://github.com/canjs/can-define/issues/239

**Comment by Alfredo-Delgado** [comment]
Update: I'd like to set up a project with the latest can-define release to see how the checkbox binding behaves. That might still be a separate issue.

**Comment by phillipskevin** [comment]
@Alfredo-Delgado can this be closed then?

**Comment by Alfredo-Delgado** [comment]
I was able to confirm via a local app using `can-define@1.4.0` that the checkbox problem exhibited in the provided jsbin is also fixed.
