### ISSUE TITLE
autofocus attribute causes setAttribute error in jsbin

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-stache#181]
This only seems to be an issue on jsbin, though I can not see any reason why. Further, the only attribute I can recreate this with is autofocus, and it happens with `autofocus=""`, `autofocus="autofocus", but not with just `autofocus`.

https://jsbin.com/limotag/1/edit?html,js,console,output

**Comment by justinbmeyer** [comment]
I think Kevin knows why this is. Someone at Bitovi explained this to me.

**Comment by justinbmeyer** [comment]
I'm closing this as I think it's something weird jsbin does to prevent hacking or something.  Will re-open if someone knows what we can do.
