### ISSUE TITLE
Conditional attribute values do not get updated

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#183]
@akagomez commented on [Mon Jul 18 2016](https://github.com/canjs/canjs/issues/2439)

`value` will not be updated when `count` changes in this scenario:

```
  <input type="text" {{#if count}}value="{{count}}"{{/if}} />
```

See this example: http://jsbin.com/lokati/3/edit?html,js,output

**Comment by phillipskevin** [comment]
This is working now: http://jsbin.com/kuwovorebu/1/edit?html,js,output.
