### ISSUE TITLE
Stache helper is called with wrong options properties

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#185]
@SergeRNR commented on [Tue Sep 06 2016](https://github.com/canjs/canjs/issues/2474)

Hi,

the [documentation](https://canjs.com/docs/can.stache.helperOptions.html) says only section helpers have "options.fn" and "options.inverse" methods. But I noticed that inline {{helper}} also has "options.fn". This method returns undefined if called.
I see it as expected behavior in [tests](https://github.com/canjs/canjs/commit/8238af274256daf408517fa735152884b6ca0cc4).

We use custom helpers as inline and section helpers and we need to distinguish if helper was called as section or not. How can we do it ?

---

@justinbmeyer commented on [Tue Apr 11 2017](https://github.com/canjs/canjs/issues/2474#issuecomment-293446839)

I'm not sure there's a way currently.  Good catch!

**Comment by chiefsmurph** [comment]
http://jsbin.com/cihulehuwo/edit?html,js,output

Isn't one possible answer to this just to check whether `helperOptions.fn` returns undefined (case of inlineHelper) or if it returns a documentFragment (case of sectionHelper)?

**Comment by andrejewski** [comment]
I think this issue can better be articulated as "how to detect if a helper is inline or sectional?" We should add to the `helperOptionsArg` an `isSection: boolean` field to let people make the distinction.
