### ISSUE TITLE
Enable mixed case binding attribute names by encoding uppercase

### ISSUE THREAD

**Issue by nlundquist** [canjs/can-stache#194]
At the present can-stache-bindings cannot directly use mixed case attribute names due to the case insensitivity of HTML. To bind to a view model property with mixed case a developer has to use a kebab-case attribute name which is converted to a camelCase property name by the binding:
```
{some-property}="otherProperty"
// binds someProperty to otherProperty
```

This is particularly difficult for ($event) bindings, which don't undergo the kebab to camel case conversion in CanJS 3.x:
```
($some-event)="doSomething()"
// el.addEventListener("some-event", ...);

// using camel case doesn't change the behaviour as can-stache converts it to kebab case to avoid the case sensitivity issues in HTML
($someEvent)="doSomething()"
// el.addEventListener("some-event", ...);
``` 
Currently there is no way in 3.x to use an event binding to bind to an event with mixed case.

To remove the need for kebab to camel case conversions in our bindings, and enable event bindings to events with mixed case names, I've proposed that we allow mixed case attributes in stache templates by encoding uppercase characters. Binding attribute names will have their uppercase characters encoded during template parsing and then decoded during binding processing. 

`{mixedCaseBinding}="otherProp"` in template may be rendered to the DOM like `{\\cmixed\\ccase\\cbinding}="otherProp"`.

Event binding could then freely use mixed case:
```
($SomeEvent) ="doSomething()"
    [can-view-parser]-> ($\\csome\\cevent)
    [can-stache-bindings] -> el.addEventListener('SomeEvent', ...)
```

To see a discussion which occurred at the initial proposal of this change refer to the [DoneJS Contributors Meeting for April 28th](https://www.youtube.com/watch?v=5z6Niq2ly2s&t=44m18s).

**Comment by rjgotten** [comment]
Something that's been nagging me on and off since the first time I ran into the kebab vs camel issue with stache:

Why the explicit serialization of binding attributes into the DOM anyway?
What's the purpose?

Wouldn't it make sense to simply track bindings via a data store paired with a DOM node like `jQuery.data` does?

**Comment by justinbmeyer** [comment]
{{#binding}}($click)="doSomething"{{/binding}}

**Comment by phillipskevin** [comment]
This is possible with the new binding syntax.
