### ISSUE TITLE
Implement slot-like replacement for can-component

### ISSUE THREAD

**Issue by mikemitchel** [canjs/can-stache#195]
Adding support in can-stache to allow can-component to have slot-like functionality:

see this issue in can-component:
https://github.com/canjs/can-component/issues/4

Also:
From: https://github.com/canjs/canjs/issues/2278
          https://github.com/canjs/canjs/issues/2429 - specify scope or context

Background on slots:

https://webkit.org/blog/4096/introducing-shadow-dom-api/
https://www.w3.org/TR/shadow-dom/#distributions
https://www.w3.org/TR/shadow-dom/#dfn-slot-element

**Comment by chasenlehara** [comment]
Shipped [`<can-slot>`](https://canjs.com/doc/can-component/can-slot.html) and [`<can-template>`](https://canjs.com/doc/can-component/can-template.html) 🎊
