### ISSUE TITLE
Memory leak with bindings inside {{#if}}

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#200]
@phillipskevin commented on [Tue May 16 2017](https://github.com/canjs/can-stache-bindings/issues/210)

From https://github.com/canjs/canjs/issues/3147#issuecomment-301749119.

I'm not positive this is a can-stache-bindings issue, but it seems most relevant so adding it here.

Here is the minimal example I could come up with to reproduce this issue:
```html
<!-- index.html -->
<div id="out"></div>
<a href="javascript://">Insert</a>
```

```js
// index.js
import Map from 'can-map';
import stache from 'can-stache';
import 'can-stache-bindings';

var data = new Map({
  foo: {
    bar: 'baz'
  }
});

var view = stache('{{#if foo}}<input type="text" (foo)="someFunction()" >{{/if}}');

(function($) {
        console.log('ready');

        var $out = $('#out');
        var inserted = false;

        $('a').click(function() {
                if (!inserted) {
                        $out.html(view(data));
                        $(this).html('Remove');
                        inserted = true;
                } else {
                        $out.html('');
                        $(this).html('Insert');
                        inserted = false;
                }
        });
}($));
```

This seems to be caused by the binding for `(foo)` never being torn down when the `<input>` is removed from the page.

I was able to reproduce this with can-map or DefineMap.

---

@phillipskevin commented on [Tue May 16 2017](https://github.com/canjs/can-stache-bindings/issues/210#issuecomment-301829831)

The same thing happens with
```html
{{#if foo}}<span>{{foo.bar}}</span>{{/if}}
```

**Comment by phillipskevin** [comment]
@andrejewski if you have time, can you look into this? I'm not 100% positive this is the actual source of the original issue, but we can go through how I reproduced it and narrowed it down to this.

**Comment by justinbmeyer** [comment]
This is a long standing issue.  The solution to this is to make sure your "top-level" view always has a containing element like `<div>{{#if foo}}<input type="text" (foo)="someFunction()" >{{/if}}</div>` and then remove that DIV, not the input.

You only need this on "top-level" views.  Component views are fine because they will always be passed a node-list.

We might be able to figure this out now that we have mutation observers. The following are random notes that I will clean up later ...

===========


```js
 stache('{{#if foo}}{{#if bar}}<input type="text" (foo)="someFunction()" >{{/if}}<div>{{foo}}</div>{{/if}}')
```

```
{{#if something}}
  <form>{{{someHTML}}}</form>
{{else}}
  <form>{{{someHTML}}}</form>
{{/if}}
```

someHTML -> "<label><span></span></label>"

**Comment by phillipskevin** [comment]
Yeah, @andrejewski and I figured this out earlier today. He is looking into a fix, but this probably means that this is not the source of the original memory leak since that code was using components.

**Comment by justinbmeyer** [comment]
@phillipskevin how was the initial component being inserted?

**Comment by phillipskevin** [comment]
```js
var renderer = can.stache("<my-main />");
document.body.appendChild(renderer());
```

You can see the code here: http://jsbin.com/wavidor/edit?html,js,output.

**Comment by justinbmeyer** [comment]
@phillipskevin yeah, that looks like it should work ... especially as only stache is being used to add / remove elements.  Is it the `{{#foo}}` binding that is leaking?

**Comment by phillipskevin** [comment]
I can't remember. I thought it was the `<option>` element that couldn't be garbage collected, but I'm not positive. Maybe @andrejewski can confirm.

**Comment by andrejewski** [comment]
Yes, @phillipskevin is right, in the [provided example]() HTMLOptionElement nodes are not collected. Here is a comparison between the initial memory profile and the post toggle-untoggle profile:
<img width="628" alt="screen shot 2017-05-23 at 6 46 21 pm" src="https://cloud.githubusercontent.com/assets/1660953/26379679/7b3e48ba-3fe8-11e7-8c23-eabec11e0ac2.png">

**Comment by pmgmendes** [comment]
Hi @andrejewski, @phillipskevin, @justinbmeyer 
I'm collecting the canjs libraries with memory related issues so I can take a decision on how and when to upgrade our application dependencies. 
Can you tell what the status of this issue? 
It seems relevant to us because we've a lot occurrences for this type of binding.
Thanks!

**Comment by andrejewski** [comment]
This issue was resolved with https://github.com/canjs/can-stache-bindings/pull/213 which was released in https://github.com/canjs/can-stache-bindings/releases/tag/v3.1.5.
