### ISSUE TITLE
{{#eq expression}} is not documented

### ISSUE THREAD

**Issue by imaustink** [canjs/can-stache#201]
__Description:__
`{{#eq expression}}` is used in many of our guides but it is not documented anywhere. Most guides link to [`{{#is expression}}`](https://canjs.com/doc/can-stache.helpers.is.html), which can be confusion to someone learning CanJS.

__Steps to reproduce:__
See example [here](https://canjs.com/doc/guides/recipes/file-navigator-simple.html#Rendertherootfolderanditscontents)

**Comment by matthewp** [comment]
They are aliases of each other. I don't think we should document both, as that would be more confusing.

**Comment by phillipskevin** [comment]
I think we just need to find places where we're using `{{#eq}}` and change them to `{{#is}}`.

**Comment by justinbmeyer** [comment]
I like eq more than is. Not sure if that matters.

**Comment by chasenlehara** [comment]
+1 on documenting both by creating `eq` docs that say “`eq` is an alias of [is](https://canjs.com/doc/can-stache.helpers.is.html)” (or vice-versa). People need to be able to find _all_ the helpers in our docs, and we can’t change people’s code to use `is`, so we need docs for both.

Also, not that it matters, but I prefer `eq` too.

**Comment by phillipskevin** [comment]
That's fine. I usually use `eq` also, I just think it might be confusing with `eq` and the `equal` converter, but this is probably something we can solve later on. I also assumed there was some reason `eq` was not documented, but if this was just never done, I agree, let's do it.
