### ISSUE TITLE
Move route helper logic to can-route

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-stache#205]
I think it would make more sense if the logic for the [routeUrl](https://github.com/canjs/can-stache/blob/c99ef1446762a9cf9948847d4d15557e9852177d/helpers/route.js#L39-L44) and [routeCurrent](https://github.com/canjs/can-stache/blob/c99ef1446762a9cf9948847d4d15557e9852177d/helpers/route.js#L46-L60) helpers (and possibly others?) were in can-route/helpers.js, and that was used in calls to registerHelper here instead.

The main reason I ran into this need is so that I can use the helpers in [react-view-models](https://github.com/canjs/react-view-models/blob/600b0bdf94f6fb035fd8ba9d31756f096b5e40bd/examples/chat/chat.js#L37).

**Comment by matthewp** [comment]
They already are in can-route, as route.url and route.current. The logic in the helpers is all helper logic. You should use route.url and route.current directly.

**Comment by christopherjbaker** [comment]
and so it is. I had seen the logic for `calculateArgs ` and not really looked at what it was doing.
