### ISSUE TITLE
Plain JS object scope dosent work with subtemplate

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#208]
@cherifGsoul commented on [Thu Apr 27 2017](https://github.com/canjs/can-view-callbacks/issues/41)

In the custom tag callback, plain object scope throws error like in this jsbin http://jsbin.com/wesinuc/edit?html,js,console,output 

---

@justinbmeyer commented on [Fri Apr 28 2017](https://github.com/canjs/can-view-callbacks/issues/41#issuecomment-298018807)

works if the context has an observable: http://jsbin.com/febakiq/edit?html,js,console,output

---

@cherifGsoul commented on [Fri Apr 28 2017](https://github.com/canjs/can-view-callbacks/issues/41#issuecomment-298053140)

@justinbmeyer I got ```scope.__cache is undefined``` http://jsbin.com/yoyise/edit?html,js,console

---

@justinbmeyer commented on [Wed May 31 2017](https://github.com/canjs/can-view-callbacks/issues/41#issuecomment-305224242)

The issue here is that `subtemplate` isn't wrapped with something that converts the data passed to it to a scope object.  This is a problem with can-stache.  

```
var frag = tagData.subtemplate({
  first: 'Justin'
  }, tagData.options)
```

**Comment by justinbmeyer** [comment]
The fix to this is to wrap the renderer so that it forces when someone calls `subtemplate`, for it to have a scope: 

https://github.com/canjs/can-stache/blob/master/can-stache.js#L236
This can be used to do the conversion: https://github.com/canjs/can-stache/blob/namedPartials/src/utils.js

**Comment by cherifGsoul** [comment]
@justinbmeyer thank you for this great summary I couldnt figure out it without your help :+1:
