### ISSUE TITLE
toFixed unexpected behavior

### ISSUE THREAD

**Issue by leoj3n** [canjs/can-stache#213]
__How often can you reproduce it?__

- [x] Always

__Description:__

Using toFixed in a stache template results in unexpected behavior.

__Steps to reproduce:__

- Visit <https://glitch.com/edit/#!/to-fixed-bug>
- Click "Show [Live]"
- Visit `/views` (<https://to-fixed-bug.glitch.me/views/>):

![image](https://user-images.githubusercontent.com/990216/26899272-3e348d6e-4b94-11e7-9a2e-1b932af582ac.png)

__Expected results:__

All instances of using `.toFixed` in the stache template **should** work.

__Actual results:__

![image](https://user-images.githubusercontent.com/990216/26899303-56cb6b5e-4b94-11e7-997b-590bd11f68ae.png)

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | *
| Browser                    | Chrome Canary
| Operating system    | MacOS

**Comment by justinbmeyer** [comment]
```js
stache.registerHelper('myHelper', function(a) {
  return a;
});

var renderer = stache('<br/>POJO<hr/>' +
                      'helper: {{myHelper(getTotal()).toFixed(2)}}<br/>' +
                      'func: {{getTotal().toFixed(2)}}<br/>' +
                      'prop: {{someProp.toFixed(2)}}<br/>');

var frag = renderer({
  someProp: 5.5,
  getTotal: function() {
    return 0.0;
  }
});

document.body.appendChild(frag);
```
