### ISSUE TITLE
SVG not rendered in IE11

### ISSUE THREAD

**Issue by Lighttree** [canjs/can-stache#242]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

`SVG` element doesn't work in `IE11`

__Steps to reproduce:__

This is JS Bin that reproduces the issue:
http://jsbin.com/tevegiyawe/1/edit?html,js,output

If you open it in `IE11` you will see that the first icon renders correctly, but the same icon from `stache` not rendered at all. The same issue valid for `SVG` sprites.
Maybe this is somehow related to `insertAdjacentHTML` at least there were some issues with other frameworks and `SVG` before.

__Expected results:__

Rendered `SVG`.

__Actual results:__

`SVG` code exists on the page, but not rendered (invisible).

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  |  3.3.0
| Browser                    |   IE11
| Operating system    |   Win 10

**Comment by Sinjhin** [comment]
This should be fixed with https://github.com/canjs/can-view-target/releases/tag/v3.1.1
