### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by dpeixoto** [canjs/can-stache#248]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
License file is not available in the repo of this module and at least in the following ones:
can-cid
can-component
can-compute
can-connect
can-construct
can-construct-super
can-ejs
can-event
can-jquery
can-list
can-list-sort
can-map
can-map-backup
can-map-define
can-model
can-route
can-stache
can-stache-bindings
can-types
can-validate-legacy
can-view-autorender
can-view-callbacks
can-view-model

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/

__Expected results:__
License file available in each can module repo

__Actual results:__

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 
| Browser                    | 
| Operating system    |

**Comment by andrejewski** [comment]
Hey @dpeixoto, we are aware of the situation and I am writing a tool to automate adding these licenses files, among other things. Thank you for compiling that list of repos, I'll be sure to point our fixer tool at them all. I opened an issue https://github.com/canjs/canjs/issues/3440 which I will close  when they are all updated. Closing this issue; thank you for your contribution.
