### ISSUE TITLE
Proposal: drop % from %special values

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#253]
People get confused by things like `%event` and we should consider dropping the `%` and handling collisions with our reserved keywords.

**Comment by justinbmeyer** [comment]
Another thing I thought about was doing this with binding syntax: 'on:dropon(event,drag,drop)=doSomething(drop)'

**Comment by phillipskevin** [comment]
closing for https://github.com/canjs/can-stache/issues/304.
