### ISSUE TITLE
PR: 259 - Add: es6 Support for can-stache

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-stache#260]
#259 - Add: es6 Support for can-stache

fails browser timeout firefox need to test local will let this open as reference

**Comment by chasenlehara** [comment]
From @matthewp’s [comment on #259](https://github.com/canjs/can-stache/pull/259#issuecomment-322501270), this sounds like something we’re not going to “fix,” so I’m closing this issue. If it’s an actual bug we need to address, it can be reopened.
