### ISSUE TITLE
debugger.js has debug code that is not removed correctly

### ISSUE THREAD

**Issue by ilyavf** [canjs/can-stache#265]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

The built version of DoneJS website throws an error on load:

> ReferenceError: Error loading "fsm@0.0.0#index.stache!done-autorender@1.3.1#src/autorender"
evaluateArgs is not defined

__Steps to reproduce:__

DoneJS project, build, load production website.

The issue was posted on gitter:
https://gitter.im/stealjs/steal?at=598cc6022723db8d5e91d33b

![image](https://user-images.githubusercontent.com/1895948/29192952-12f32cd0-7e2c-11e7-8472-a603f2169822.png)

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  |  3.5.0
| Browser                    |  Chrome
| Operating system    |  MacOS

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-stache/pull/266.
