### ISSUE TITLE
Add "as" functionality to #with

### ISSUE THREAD

**Issue by James0x57** [canjs/can-stache#274]
Similar to what we have for the `{{#each EXPRESSION as KEY}}` context:
https://canjs.com/doc/can-stache.helpers.each.html#___eachEXPRESSIONasKEY__FN__else__INVERSE___each__

Would be great to have `{{#with EXPRESSION as KEY}}`:
https://canjs.com/doc/can-stache.helpers.with.html

It helps you be specific about the context you're pulling from.

**Comment by justinbmeyer** [comment]
I wonder if we could do 'with foo=bar zed=ted'

**Comment by justinbmeyer** [comment]
I would start with just `#with`.

**Comment by justinbmeyer** [comment]
make sure to consider two-way values.

**Comment by justinbmeyer** [comment]
we could also make this work with partials:

```
{{>partialName foo=bar zed=ted}}
```

**Comment by Sinjhin** [comment]
An initial test was written in this PR: https://github.com/canjs/can-stache/pull/299

**Comment by phillipskevin** [comment]
This was added in #299.
