### ISSUE TITLE
Replace %special syntax by accessing via scope object

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-stache#287]
Per conversation with @justinbmeyer we want to get rid of all the [`%special`](https://canjs.com/doc/can-stache/keys/special.html)  keywords and access them with a scope object like:
```js
{{#each tasks}}
  <li>{{scope.index}} {{name}}</li>
{{/each}}
```
rather than
```js
{{#each tasks}}
  <li>{{%index}} {{name}}</li>
{{/each}}
```

This would mean that `scope` would be reserved.

**Comment by phillipskevin** [comment]
Closing in favor of https://github.com/canjs/can-stache/issues/304 since it is the same issue and that one has more detail.
