### ISSUE TITLE
Add "as" functionality to #expression context setups

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#301]
From https://github.com/canjs/can-stache/issues/274.

Would be great to have `{{#expression as KEY}}`:
https://canjs.com/doc/can-stache.tags.section.html

**Comment by justinbmeyer** [comment]
I think we should avoid `as` and deprecate it's use in #each : https://github.com/canjs/can-stache/issues/300

**Comment by frank-dspeed** [comment]
@phillipskevin i think this can be clossed as we got consens with 4.0 about the as method
