### ISSUE TITLE
Make dev.warn tests resilient to new warnings

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#302]
We have many [tests](https://github.com/canjs/can-stache/blob/8005a640a50ac7a15cf0410c48e417c6a97dcdfa/test/stache-test.js#L5502) that assert the value of a warning message. When other `can-*` repos add new warnings, these tests often break. We should use a flag to only assert the value of warning messages when we're making the `stache(...)` call we're trying to test. We should be able to do this with a simple flag:

```js
var checkWarnings = false;
canDev.warn = function(text) {
    if (checkWarnings){ 
        equal(text, texts[count++]);
    }
};

...

checkWarnings = true;
stache(...);

...
```

**Comment by phillipskevin** [comment]
Another option (given by @christopherjbaker via @imaustink) is to only assert if the warning matches the expected value along with `expect(...)` to make sure the correct number of warnings are given like  [this test](https://github.com/canjs/can-stache-bindings/blob/fbda37396e87c6a1f48ac1a60f757325731bbad2/test/bindings-test.js#L2749).

**Comment by christopherjbaker** [comment]
I think the best option would be a built in mechanism, something like `canDev.mockWarn('expected warning')` or `canDev.mockWarn([ 'expected warning', 'other warning' ])`. Besides simplifying the tests instead of having that code every time, it would also make future changes to this logic simpler. =]

**Comment by phillipskevin** [comment]
We may want to create a `can-test-helpers` module for useful functions like this.
