### ISSUE TITLE
Replace *variable and %special with `scope`

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#304]
> Note: A discussion of this topic can be [found on youtube](https://youtu.be/GG5-tUBz2-A?t=2369).

This issue represents a combination of several other issues with the goal of cleaning up some of the uglier, less "handlebars" and "javascript" bits of `can-stache`.

- move any non-contextual access or mutations to a reserved `scope` variable
- make `#with` and `#each` use hash params

### *variable => scope.var.variable

Move access to template variables (references scope) to `scope.var.`.  Examples:

```html
<can-import from="date-helpers" value:to="*dateHelpers"/>
{{*dateHelpers.prettyDate( date )}}
=>
<can-import from="date-helpers" value:to="scope.var.dateHelpers"/>
{{scope.var.dateHelpers.prettyDate( date )}}
```

### %special => scope.special

Allow special keys to be looked up directly on `scope.` Examples:

```html
{{#each items}} {{%index}} {{/each}}
=>
{{#each items}} {{scope.index}} {{/each}}
```

```html
<div on:click="doSomething( %element, %event, %arguments )"/>
=>
<div on:click="doSomething( scope.element, scope.event, scope.arguments )"/>
```

### Access to other values:

- Helpers passed to the template `scope.helpers.helperName`
- Partials passed to the template `scope.partials.partialName`
- Tags passed to the template `scope.tags.component-name`
- `<can-template name="NAME">`s passed to the template `scope.templates.NAME`
- Inline partials created in the template `scope.partials.partialName`
- The current renderer `scope.view`

### Implementation Details 

1. Each template has a references scope, this should be expanded to be a special object that looks like: `{vars: {}, helpers: {}, partials: {}, templates: {}, view: renderer, optionsScope: optionsScope}`.  This object should be the `templateContext`.  
  - When a `partial` is looked up on the `templateContext`, it should look in its partials, and then explore the `optionsScope`.
  - When a `helper` is looked up, it should look in its helpers, and then explore the options scope, and then the registered helpers.
2. `scope[can.getKeyValue]` needs special rules.  It probably should first look up in the references scope, then in the "notContext" contexts, then in the normal contexts.  
3. In 4.0, I would like to change the use of the `options` arg to renderers `template(data, options)` to essentially set the `templateContext`.
  - I'd also like to think about special events being registered. `<can-import from="drag-drop" value:merge-to="scope.events"/>`

## make `#with` and `#each` use hash params

- [x] - [`{{#with firstName=person.first}}`](https://github.com/canjs/can-stache/issues/274)
- [x] - [`{{#each items item=value num=index}}`](https://github.com/canjs/can-stache/issues/300)

**Comment by phillipskevin** [comment]
This is done in `major`.
