### ISSUE TITLE
Incorrect warning, stache expected a closing {{/div}} tag

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-stache#321]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
Not sure yet what markup is causing the issue, but

```js
unexpected close tag {{/eq}} expected {{/div}}
```

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 3.8.0
| Browser                    | 61.0.3163.100
| Operating system    | 10.13 (17A365)

**Comment by christopherjbaker** [comment]
I dug into the code which logs this error a bit. There is only one place that has an error like this, and it is only called when parsing special tags, not html tags (there is a similar error for html tags, but it explicitly include brackets in the text, so cannot be the culprit). My only guess as to the cause of this is that there is as `{{div}}` opening tag, and is thus expecting it to close. Without being able to recreate this, I'm not sure what else can be done here. Can you provide any related markup?

**Comment by mjstahl** [comment]
I wish I could. The application is rather large and I saw it on the console when rendering the application.

I did a project search for `{{div}}` and no result were returned. I will just have to keep an eye out.

**Comment by christopherjbaker** [comment]
We are in process of making those errors more useful. Once that is finished, if you can find the error again, that might be more helpful. =]

**Comment by justinbmeyer** [comment]
You should be able to set a debugger in the log and walk up the stack to see which file it is in.

**Comment by phillipskevin** [comment]
It's pretty easy to reproduce this:
```
<div>
{{#if foo}}
</div>
{{/if}}
```

Here is a JSBin: http://jsbin.com/becexahixu/1/edit?js,console,output.

The error is coming from: https://github.com/canjs/can-stache/blob/675fa5c3e9f09023b00566657bfce973654ec89c/can-stache.js#L98.
