### ISSUE TITLE
partial tag is missed in the readme

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-stache#34]
in https://github.com/canjs/can-stache/tree/master/docs/tags there is no `partials.md`
in the folder above, it is located.
in the readme `partials key` is not documented
on the new canjs website (http://canjs.github.io/canjs/doc/can-stache.helpers.partial.html) the url contain `helpers`?
@matthewp something wrong there?

**Comment by matthewp** [comment]
It's here, wrong folder I guess: https://github.com/canjs/can-stache/blob/master/docs/partials.md
