### ISSUE TITLE
scope.index doesn't work with Arrays

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-stache#358]
https://jsbin.com/besuwadifu/1/edit?html,js,console,output

the `scope.index` special var works fine when iterating a DefineList, but is empty when iterating an Array.  The two cases should be the same: `scope.index` should hold indexes for Array iteration as well.

@phillipskevin noted that some of the Array handling code in can-stache is setting `scope.key` when it should be setting `scope.index`

**Comment by phillipskevin** [comment]
duplicate of https://github.com/canjs/can-stache/issues/356.
