### ISSUE TITLE
nested methods not warning

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#377]
This might need to be in scope, but the following does not warn in todomvc `if( isEditing(this) )`

<img width="401" alt="todomvc-observe_html_ ___dev_canjs" src="https://user-images.githubusercontent.com/78602/32996328-c6efe174-cd46-11e7-8d09-64b99fbfa649.png">

it needed to be `../isEditing`

**Comment by justinbmeyer** [comment]
There's a similar problem with the focused attribute:

<img width="272" alt="todomvc-observe_html_ ___dev_canjs" src="https://user-images.githubusercontent.com/78602/32996336-e24e550e-cd46-11e7-9916-899700f5b6be.png">

**Comment by phillipskevin** [comment]
when I load the todomvc example on master I do see warnings for these:

![image](https://user-images.githubusercontent.com/5851984/33089758-3cf6bd54-ceb7-11e7-95a2-0445b8455a24.png)

**Comment by phillipskevin** [comment]
@justinbmeyer perhaps the warnings were `steal-remove`d in the version you were looking at?

**Comment by justinbmeyer** [comment]
I'm latest everything, I still see it within my example.  Furthermore, I started seeing the following unnecessary warnings:

![localhost_8080_canjs_docs_can-guides_experiment_todomvc_todomvc-observe_html](https://user-images.githubusercontent.com/78602/33244489-be2b902a-d2bd-11e7-9cff-438fee9c9f89.png)

**Comment by justinbmeyer** [comment]
It also seems these should be warning but are not:

```js
<a href="{{routeUrl(filter=undefined)}}"
					{{#routeCurrent(filter=undefined)}}class='selected'{{/routeCurrent}}>All</a>
```
