### ISSUE TITLE
Problems while using @index and %index

### ISSUE THREAD

**Issue by nriesco** [canjs/can-stache#379]
__How often can you reproduce it?__ 

- [ ] Always
- [x] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

This code won't work:

```
{{#if mainModelPromise.isResolved}}
  {{#each mainModelPromise.value}}
    Line number: {{@index}}<br> <!-- this will show 0 for each line -->
  {{else}}
    no results
  {{/each}}
{{/if}}
```

__Steps to reproduce:__

This happens in a component, generated using donejs.

__Expected results:__

I expected the number to increase on each line but it didn't

__Actual results:__

Every line had 0's instead of 0, 1, 2

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 3.6.0
| Browser                    | Chrome / OSX
| Operating system    | Mac osx 10.13

**Comment by nriesco** [comment]
Some extra info:

`{{@index}}` nor `{{%index}}` work

`{{@index 1}}` prints 1 and `{{%index 1}}` prints 0

**Comment by nriesco** [comment]
I tried upgrading to version 3.13.5 and got the same results.

On the other hand using `{{#each(mainModelPromise.value)}}` now works!

**Comment by imaustink** [comment]
@nriesco I am so far unable to replicate this problem with either `%index` or `@index`. Could you perhaps share more details or, even better, more code to help me replicate this issue?

**Comment by phillipskevin** [comment]
Here is the start of the conversation about this issue @imaustink: https://gitter.im/canjs/canjs?at=5a1235e50cef4fed2ebd73f0.

**Comment by nriesco** [comment]
Thanks @imaustink for your patience, I was using an `each` within an `each` so actually my loops were of length 1. No bug really only a bad design pattern on my side.
