### ISSUE TITLE
Having two version of can-stache can lead to missing helpers

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#394]
Having two versions of `can-stache` can cause missing helpers since the `getHelper` method looks in the stateful `helpers` object here: https://github.com/canjs/can-stache/blob/4d99191755879ed25f09c1c47d0fbb59f426fa77/helpers/core.js#L458

We should extract this out and throw an error if multiple versions are loaded.

This was reported on Gitter: https://gitter.im/canjs/canjs?at=5a21cc4cffa3e37919e554ec.

**Comment by frank-dspeed** [comment]
@phillipskevin i think but i am not sure the whole stache helpers even the core once could get extra packages maybe the core once in a collection 4.0 is prepared for that already i think.

**Comment by phillipskevin** [comment]
This is fixed in 4.0 since it is using the https://github.com/canjs/can-stache-helpers/ package now.
