### ISSUE TITLE
Add common converters

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#40]
Related: https://github.com/canjs/can-stache/pull/35

I think we need:

 - [ ] - `<input type='checkbox' {($checked)}=inList(item, list)/>`
 - [ ] - `<select {($value)}="toString(~someValue)">` - converts `null`, `undefined`, `5`, `false` and as much as possible to a string representation and vice versa.

**Comment by matthewp** [comment]
Closed in favor of https://github.com/canjs/can-stache-bindings/issues/24 and https://github.com/canjs/can-stache-bindings/issues/25
