### ISSUE TITLE
Using stache's each helper causes computes to be called more than once

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache#402]
This gist demonstrates the bug: https://gist.github.com/matthewp/43ea479065b1dc1d95a8cfe6e23a9cb7

Here `thingsPromise` is called multiple times.

**Comment by matthewp** [comment]
Note that this doesn't happen using `{{#list}}{{/list}}` syntax, so pretty sure the problem is in each.

**Comment by phillipskevin** [comment]
this is fixed in `major`.
