### ISSUE TITLE
"Unable to find key or helper" warning when property is defined on the viewModel

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache#405]
This is can-stache 4.x prerelease: 

https://gist.github.com/matthewp/eea34b36f5bc3595f93bb02748555de2

This key is defined on the viewModel, but is currently undefined. I thought we had said that it should not warn.

**Comment by phillipskevin** [comment]
The `canReflect.hasKey` check [here](https://github.com/canjs/can-stache/blob/99ab7005d17511b655092c5b784018df5d39136d/expressions/lookup.js#L28) should prevent this warning. I'll re-check this today.

**Comment by phillipskevin** [comment]
Rechecked with `can-stache@4.0.2` and this warning is gone now.
