### ISSUE TITLE
Provide an easier way to do scope lookup

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache#419]
# The Goal

Make it easier to upgrade templates that depend on implicit scope lookup.

# The Problem

In upgrade templates to can-stache 4.0-pre, the biggest difficulty has been in resolving nested sections and figuring out where in the scope.

Here's an example of one I came across:

```handlebars
<tbody>
  {{#each(~games.getRoundsWithGames())}}
    <tr>
      <td>{{.}}</td>
      {{#each(courtNames)}}
        <td>
          {{#games.getGameForRoundAndCourt(.. , .)}}
            <a href="{{routeUrl(gameId=id)}}">
              {{#teams.getById(homeTeamId)}}{{color}}{{/teams.getById}}
              v
              {{#teams.getById(awayTeamId)}}{{color}}{{/teams.getById}}
            </a>
...
```

Within each of these `{{#each}}` loops I had to check each binding to see what it was trying to reference. To do this I had to examine what its parent `#each` was returning.

So for example, to figure out `games.getGameForRoundAndCourt(.. , .)` I had to:

1. Look at the implementation of `each(courtNames)` to see if it returned something with a `games` property.
1. Look at the implementation of `each(~games.getRoundsWithGames())` to see if it returned something with a `games` property.
1. See if the component ViewModel had a `games` property.

Eventually my template looked like:

```handlebars
<tbody>
  {{#each(~games.getRoundsWithGames())}}
    <tr>
      <td>{{.}}</td>
      {{#each(../courtNames)}}
        <td>
          {{#../../games.getGameForRoundAndCourt(.. , .)}}
            <a href="{{routeUrl(gameId=id)}}">
              {{#../../../teams.getById(homeTeamId)}}{{color}}{{/../../../teams.getById}}
              v
              {{#../../../teams.getById(awayTeamId)}}{{color}}{{/../../../teams.getById}}
            </a>
...
```

This was a lot of work to figure out. I suppose I could have used `scope.find` at each level:

```handlebars
<tbody>
  {{#each(~games.getRoundsWithGames())}}
    <tr>
      <td>{{.}}</td>
      {{#each(scope.find("courtNames"))}}
        <td>
          {{#scope.find("games").getGameForRoundAndCourt(.. , .)}}
            <a href="{{routeUrl(gameId=id)}}">
              {{#scope.find("teams").getById(homeTeamId)}}{{color}}{{/scope.find("teams").getById}}
              v
              {{#scope.find("teams").getById(awayTeamId)}}{{color}}{{/scope.find("teams").getById}}
            </a>
...
```

But it's not super-intuitive how to write this sort of code, especially the closing part.

# Suggested Solution

It would be nice if there was a shortcut for `scope.find(key)` that makes it easier to upgrade templates that depend on scope lookup. This would have to be some special character that doesn't have a current usage. I don't particularly care on what character it is, so I'll use `+` in this example

```handlebars
<tbody>
  {{#each(~games.getRoundsWithGames())}}
    <tr>
      <td>{{.}}</td>
      {{#each(+courtNames)}}
        <td>
          {{#+games.getGameForRoundAndCourt(.. , .)}}
            <a href="{{routeUrl(gameId=id)}}">
              {{#+teams.getById(homeTeamId)}}{{color}}{{/+teams.getById}}
              v
              {{#+teams.getById(awayTeamId)}}{{color}}{{/+teams.getById}}
            </a>
...
```

**Comment by justinbmeyer** [comment]
Aren’t most of the walkups for the viewModel? Could scope.root be used?

**Comment by justinbmeyer** [comment]
I’d prefer to avoid a special character and just introduce find, canFind, etc as a special method.

**Comment by justinbmeyer** [comment]
I think the closing part can just be {{/}}. The rest is optional.

**Comment by justinbmeyer** [comment]
I still think either viewModel or root as a global makes a lot of sense.

**Comment by matthewp** [comment]
How about an option in stache that enables implicit scope walking. This could then be passed through by a can-component option:

```js
Component.extend({
  tag: "game-details",
  implicitScopeWalking: true
});
```

We could then deprecate this option immediately and then remove it in 5.0 or 6.0.  This would be similar to how leakScope: true helped with migrating those types of components from 2.3 - 3.0.

**Comment by phillipskevin** [comment]
Wouldn't adding this `implicitScopeWalking` option and then deprecating it immediately put people in the same position they're in now?

All of these implicit scope walk-ups should have warnings in 3.0 now so people can figure this stuff out before migrating to 4.0.

I think adding an option just kicks the issue down the road.

**Comment by justinbmeyer** [comment]
Turning on implicit scope walking does kick the can down the road, but it makes upgrading easier ... an upgrade that still has the benefits of queues and debugging AND still demands a bunch of other stache changes.

**Comment by matthewp** [comment]
The issue I see is that we don't have a good alternative to scope walking today. `{{#each ../../../games.someFunction(../../)}}` is awkward to write and not at all obvious to read. Ideally the best solution would be some way to name contexts within the template, and then everything has to be explicitly referenced. This is like the `{{each root.gamesFor(court) as game}}` idea (not sure what the status is of this idea). So I see this issue as a stopgap until a better solution is discovered.

**Comment by phillipskevin** [comment]
You can do that today. `{{#each(root.gamesFor(court), game=value)}}`.

**Comment by matthewp** [comment]
Ok, is this specific for `#each` or available to all block helpers? Also it would be nice to be able to declare variables local to some section. Particularly for the top-level:

```js
{{var gamesFor=root.gamesFor}}

{{#each(root.gamesFor(court), game=value)}}
```

Trying to think about how each reference could be explicit.

**Comment by phillipskevin** [comment]
It's available for `each` and `with`.

**Comment by phillipskevin** [comment]
These are the docs that the 3.0 warning link to that try to explain the options: https://canjs.com/doc/can-stache.scopeAndContext.html#PreventingScopeWalking.

**Comment by matthewp** [comment]
Closing in favor of https://github.com/canjs/can-stache/issues/420
