### ISSUE TITLE
Create helper for creating reference variables that can be read without scope.vars

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#426]
I think we should create a `let` (or something like that) helper that will store variables in a map in the TemplateContext that will always be checked if a key is not found in the context.

You could use this for accessing things like `scope.root` with whatever key you want like:

```html
{{ let("vm", scope.root) }}

<ul>
  {{#each(items, val=value)}}
	<li>{{vm.func(val)}}</li>
  {{/each}}
</ul>
```

This helper will do something like:

```js
stache.addHelper("let", function(key, value, options) {
    canReflect.setKeyValue(options.scope.templateContext.letVariables, key, value);
});
```

Then we will add a block similar to https://github.com/canjs/can-view-scope/blob/4d563f2c94ae836b9e7bf79d51076d5aa5ab7a3f/can-view-scope.js#L294-L302

that does something like `observeReader.read(this.templateContext.letVariables, keyReads);`

**Comment by phillipskevin** [comment]
Some working(ish) code is here: https://github.com/canjs/can-view-scope/tree/let-variables.

**Comment by justinbmeyer** [comment]
Could it just be the hash expression?

{{vm=scope.root}}

**Comment by phillipskevin** [comment]
It could. Making it a helper doesn't require parser changes though.

We could do

```
{{let vm=scope.root}}
```

**Comment by justinbmeyer** [comment]
@phillipskevin yeah, but the parser pretty much handles this expression already.

**Comment by justinbmeyer** [comment]
let exists!
