### ISSUE TITLE
Improve docs on loading templates

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache#429]
A few suggestions to improve the docs:

- Replace the steal-stache mention in the `stache()` signature’s docs with a link to the page on loading templates; still explicitly mention at least steal and webpack here
- Rename the Template Acquisition page to Loading Templates (or something more simple like that)
- Expand the Module Loaders section on that page to mention the same info that’s on [Setting Up CanJS](https://canjs.github.io/next/doc/guides/setup.html)

**Comment by justinbmeyer** [comment]
https://canjs.com/doc/can-stache.html#Loadingtemplates does a good job now I think
