### ISSUE TITLE
#if expression not calling method when the object is replaced.

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-stache#459]
with a template like:

```html
{{#if(player.isNew())}}Create{{else}}Update{{/if}}
```

and the following code to render it

```js
var Player = DefineMap.extend("Player", {
  __isNew: {
    default: true
  },
  isNew: function() {
    return this.__isNew;
  }
});

var VM = DefineMap.extend("VM", {
  player: {
    Type: Player,
    Default: Player
  }
});
var map = new VM();

var div = doc.createElement("div");
var frag = template(map);
```

When `player` is replaced with a new instance, the template does not reflect the `isNew()` value.

```js
map.player.__isNew = false;
QUnit.equal(innerHTML(div), "Update");

map.player = new Player();
QUnit.equal(innerHTML(div), "Create"); // throws!!!!
```

**Comment by m-mujica** [comment]
Breaking test: https://github.com/canjs/can-stache/pull/460

**Comment by justinbmeyer** [comment]
What does `logWhatChangesMe(div)` show if you wrapped the template in a div?  Something should be listening on `vm.player`, but its not.

**Comment by cherifGsoul** [comment]
It seems that the issue was already fixed, I ran travis and the build was successful, I close this and feel free to reopen if there's something I missed.
