### ISSUE TITLE
Fix setting xlink:href in 2.3 ~5

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#46]
From https://github.com/canjs/canjs/pull/2438

Related: https://github.com/canjs/canjs/issues/2384

**Comment by imjoshdean** [comment]
xlink attributes not getting properly set is a `can-util` issue and I will duplicate this issue there.

Regarding the related issue with https://github.com/canjs/canjs/issues/2384, I don't feel it is accurate. You can't just use a `<use/>` tag without wrapping it in an `<svg/>` tag. Is this something we want to support @justinbmeyer?
