### ISSUE TITLE
makeSimpleHelper should use canReflect

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-stache#473]
https://github.com/canjs/can-stache/blob/master/helpers/core.js#L342-L344

```
            while (val && canReflect.isValueLike(val)) {
                val = canReflect.getValue(val);
            }
```

**Comment by justinbmeyer** [comment]
I think he's now talking about: https://github.com/canjs/can-stache/blob/master/helpers/core.js#L352

**Comment by justinbmeyer** [comment]
https://github.com/canjs/can-stache/blob/2a433d3c23c91fa0ddfa6af45eb0a6b39324f47a/helpers/core.js#L352

**Comment by christopherjbaker** [comment]
yes, that. forgot to lock the link to a commit.
