### ISSUE TITLE
Converter naming convention

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache#48]
From private conversations, should converters have a special naming convention? For example:

```handlebars
<select {($value)}="string-to-any( ~index-to-selected(people, ~person) )">
```

These are [converter helpers](http://canjs.github.io/canjs/doc/can-stache.registerConverter.html). They have both a getter which is used to set the element's `value` and a setter which is used to set the scope value in some way.

converter helpers are cool.

However, should they look differently from normal helpers (which are camelCase) to convey the fact that they are two-way rather than one-way like normal helpers?  Does using kebab case aid in distinguishing them or hinder understanding?

**Comment by alexisabril** [comment]
If there's no technical consideration and this is truly just hyphen vs camelCase, I believe we should remain consistent with how we use helpers elsewhere.

**Comment by justinbmeyer** [comment]
Closing for now.  We can reopen post 3.0.

**Comment by matthewp** [comment]
What is the reason for closing this?

**Comment by matthewp** [comment]
Moved to https://github.com/canjs/can-stache-converters/issues/5

**Comment by justinbmeyer** [comment]
3.0 has been released with kebab-case, so I figured the discussion was over. (I've been closing anything close to "stale" to reduce our 100s of issues across all projects)
