### ISSUE TITLE
Add support for multiple keys in #if

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache#489]
Every once in a while I find myself writing code like this to check for multiple conditions:

```handlebars
{{#if(condA)}}
  {{#if(condB)}}
    Yay
  {{else}}
    Nay
  {{/if}}
{{else}}
  Nay
{{/if}}
```

This would be a little easier to read and write if I could do the following:

```handlebars
{{#if(condA && condB)}}
  Yay
{{else}}
  Nay
{{/if}}
```

It’d be nice if `#if` could also support `||`, to transform a template like this:

```handlebars
{{#if(condA)}}
  Yay
{{else}}
  {{#if(condB)}}
    Yay
  {{else}}
    Nay
  {{/if}}
{{/if}}
```

…to this:

```handlebars
{{#if(condA || condB)}}
  Yay
{{else}}
  Nay
{{/if}}
```

I’m not sure if there are any issues with adding support for `&&` and `||` in a backwards-compatible way, but I think this would improve the readability of stache templates and make it easier for new users (I think I’ve been asked about this ~50% of the time I’ve presented CanJS at a meetup).

**Comment by phillipskevin** [comment]
related to https://github.com/canjs/can-stache/issues/474.

**Comment by justinbmeyer** [comment]
and and or make this possible
