### ISSUE TITLE
Wrong scope 'switch' inside 'each' loop

### ISSUE THREAD

**Issue by Kleppo** [canjs/can-stache#509]
Problem, when 'switch' used inside an 'each' loop,
the scope is changed so I need to put '../' in front of every property..

**jsbin**: 
https://jsbin.com/lojozawape/1/edit?html,js,console,output

**Comment by chasenlehara** [comment]
I think this was fixed in [can-stache 4.15.11](https://github.com/canjs/can-stache/releases/tag/v4.15.11)
