### ISSUE TITLE
Infinite loop when using setVal

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-stache#52]
See https://github.com/donejs/donejs/issues/697

**Comment by marshallswain** [comment]
I'll make a test for this

**Comment by justinbmeyer** [comment]
@marshallswain any progress on this?

**Comment by christopherjbaker** [comment]
I spoke with @marshallswain, and he said that it was a pretty clear failure with the provided code (after removing the `return`). I recreated both the promise and setVal cases, and both are working. It appears that this got fixed sometime in the last 8 months.

http://jsbin.com/woruvac/edit?js,console,output

**Comment by christopherjbaker** [comment]
@justinbmeyer Should I create test cases, or just close it?

**Comment by justinbmeyer** [comment]
I did a decent amount of work around `setVal`, all of which had tests.  I think it's ok to close then.
