### ISSUE TITLE
scope.top and scope.vm

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-stache#526]
when i using `scope.root` i get a warning:
```scope.root` is deprecated. Use either `scope.top` or `scope.vm` instead.```

if i using `scope.top` or `scope.vm` the object is empty.

i am using can-stache 4.4.0

**Comment by justinbmeyer** [comment]
Which version of can-view-scope are you using?

**Comment by pYr0x** [comment]
i created a donejs 2.0 app.
there is no `can-view-scope` in my package.json file 
here are my dependencies:
```
dependencies": {
    "can-ajax": "^1.1.4",
    "can-component": "^4.0.2",
    "can-connect": "^2.0.2",
    "can-define": "^2.0.1",
    "can-route": "^4.1.0",
    "can-route-pushstate": "^4.0.1",
    "can-set": "^1.5.1",
    "can-stache": "^4.1.0",
    "can-stache-bindings": "^4.2.1",
    "can-stache-route-helpers": "<2.0.0",
    "can-view-autorender": "^4.0.0",
    "can-zone": "^0.6.13",
    "done-autorender": "^2.0.0",
    "done-component": "^2.1.0",
    "done-css": "^3.0.2",
    "done-serve": "^2.0.0",
    "generator-donejs": "^2.1.0",
    "jquery": "^3.3.1",
    "js-cookie": "^2.2.0",
    "steal": "^1.6.5",
    "steal-less": "^1.2.2",
    "steal-stache": "^4.0.1"
  }
```

**Comment by pYr0x** [comment]
@phillipskevin see this repo
https://gitlab.com/pYr0x/spa-medicalpad
the error is in src/index.stache

`<x-navigation app:from="scope.root"></x-navigation>`
and
`<x-login app:from="scope.root"></x-login>`

if you change `<x-login app:from="scope.root"></x-login>`
into `<x-login app:from="scope.top"></x-login>`
the app is not working and a warning is shown `index.stache:26: Unable to find key "scope.vm".`

**Comment by phillipskevin** [comment]
Sorry, I should have posted earlier. I think this is probably an issue because the scope is not marked as `viewModel: true` by done-autorender (or done-ssr?) like it is in can-component: https://github.com/canjs/can-component/blob/master/can-component.js#L358.

**Comment by phillipskevin** [comment]
@pYr0x & @chasenlehara this is fixed in https://github.com/donejs/autorender/releases/tag/v2.1.2.
