### ISSUE TITLE
this:from='.' not working with non-serializable properties

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-stache#540]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
i have a test like this,
```
it("component with data", function (done) {
    const vm = new ViewModel({
      "apiEndpoint": "oip",
      organizations: 1,
      stations: 2,
      period: 3
    });
    const frag = stache("<x-chart-signal this:from='.'></x-chart-signal>")(vm);
    document.getElementById("mocha-fixture").appendChild(frag);
  });
```
where i want the viewmodel passed into the components vm.
all works, except the `apiEndpoint` property. this property is undefined in `x-chart-signal`

**Comment by pYr0x** [comment]
Second, I want the components VM to be set by vm

**Comment by chasenlehara** [comment]
I think this already works: https://jsbin.com/bubuxoqeve/2/edit?html,js,output

@pYr0x, would you mind creating a JS Bin showing the issue?

**Comment by pYr0x** [comment]
see this repo https://github.com/pYr0x/this
1. `npm i`
2. `http-server`
3. open index.html
4. see console

**Comment by phillipskevin** [comment]
It's not because of the camelCase in your app. It looks like it is just not setting non-serializable properties: https://github.com/pYr0x/this/blob/c2a9ed440d0a4e8f45fcd51dbb4a0015a967a6dc/signal.js#L14.

This isn't related to bindings at all. The same thing happens with this code:

```
var Parent = can.DefineMap.extend({
  prop: {
    type: "string",
    serialize: false
  },
  
  serializableProp: {
    type: "string"
  }
});

var parent = new Parent({
  prop: "foo",
  serializableProp: "bar"
});

var child = new can.DefineMap(parent);

console.log(child); // -> { serializableProp: "bar" }
```

I think this is working correctly.

**Comment by phillipskevin** [comment]
Yes, it's not replacing the VM. It's setting the initial values of the VM.

**Comment by matthewp** [comment]
@pYr0x's expectation was that this would replace the VM. I am conflicted on which it should do. cc @justinbmeyer

**Comment by pYr0x** [comment]
@phillipskevin why is this jsbin working?
https://jsbin.com/bubuxoqeve/edit?html,js,output

**Comment by matthewp** [comment]
@pYr0x there are no non-serializable props unlike in the github project of yours.

**Comment by pYr0x** [comment]
sorry i was not updating the jsbin
https://jsbin.com/wevenehaqo/1/edit?html,js,output

**Comment by matthewp** [comment]
@pYr0x That's different from how your github project works. You should make it so that the definemap being passed *in* has non-serializable property.

**Comment by pYr0x** [comment]
@phillipskevin @matthewp @chasenlehara @justinbmeyer  i am confused and i dont know what the right behaviour should be.
as kevin pointed out. the problem is the `serialize` property in the viewmodel object i created.
for now i changed my test to:
```
it("component with data", function (done) {
    const frag = stache("<x-chart-signal this:from='.'></x-chart-signal>")({
      apiEndpoint: "oip",
      organizations: 1,
      stations: 2,
      period: 3
    });
    document.getElementById("mocha-fixture").appendChild(frag);
  });
```

i am not sure what `this:from='.'` exactly  does.

setting all **properties** except
  - virtual properties
  - getters
  - serialized=false properties
to the child component?

**Comment by phillipskevin** [comment]
`can-stache-bindings` is [creating the viewModel for your `<x-chart-signal>` component](https://github.com/canjs/can-stache-bindings/blob/82ce7c98fdccd6558d3c908b6b7b183e1258b0d2/can-stache-bindings.js#L170-L171).

At that line, `bindingsState.initialViewModelData` is your [`vm`](https://github.com/pYr0x/this/blob/c2a9ed440d0a4e8f45fcd51dbb4a0015a967a6dc/index.js#L4-L7).

`can-define` then reads each property from `vm` in [define.setup](https://github.com/canjs/can-define/blob/2e1b747a4aba0a2185d54ef827d46496a69dcb18/can-define.js#L966), which calls [`canReflect.getOwnEnumerableKeys` in DefineMap](https://github.com/canjs/can-define/blob/2e1b747a4aba0a2185d54ef827d46496a69dcb18/map/map.js#L497). Like you suspected, this is excludes getters and properties that are `serialize: false`.

It then sets each property on the `<x-chart-signal>` ViewModel.

**Comment by chasenlehara** [comment]
Closing this because I don’t think this uncovered any bugs.

**Comment by justinbmeyer** [comment]
@pYr0x do you remember the use case for this?  I'm working on can-component's docs.  Thanks!
