### ISSUE TITLE
addConverter is not documented

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#556]
but registerConverter is, though I think `addConverter` is the more useful (and necessary) one that can actually do child->parent conversion.  It actually adds `isLiveBound`:

https://github.com/canjs/can-stache/blob/master/helpers/converter.js#L24

Btw, do we need a better name for `isLiveBound`?  Could we call it `callWithObservableValues`?

**Comment by phillipskevin** [comment]
`isLiveBound` is bad, but I'm not sure what a better name would be. It's not really `callWithObservableValues`... It's just `dontGetValueOfArguments`.

https://github.com/canjs/can-stache/blob/fca8bdcd3829fd84d0c708de8ce52406484b7141/expressions/call.js#L42-L48

**Comment by chasenlehara** [comment]
I think this can be closed because we have `addConverter` docs now: https://canjs.com/doc/can-stache.addConverter.html
