### ISSUE TITLE
Provide an API to create a renderer from a template

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache#57]
```html
<script type="text/stache" id="template">
  <span>{{name}}</span>
</script>

<script type="text/steal-module">
  var stache = require("can-stache");

  var render = stache.querySelector("#template");
</script>
```

Not sure on the name, here's some options:

* **.querySelector(selector)**: Matches the native API, but is long.
* **.select(selector)**: Shorter, but less clear maybe
* **.$(selector)**: jQuery-like, possibly confusing.
* **.from(selector)**

----

Code for this function is essentially just:

```js
function qs(selector) {
  var script = DOCUMENT().querySelector(selector);
  var txt = script.innerHTML;
  return stache(txt);
}
```

**Comment by BigAB** [comment]
`.fromElement()`, `.fromDOM`, `fromSelector`

**Comment by justinbmeyer** [comment]
I'm going with `from`.  CanJS favors a reasonable terseness over explicitness.

**Comment by justinbmeyer** [comment]
Actually ... I think this has to load by id.  can-simple-dom doesn't support `querySelector`

**Comment by matthewp** [comment]
What's the use-case for using this feature in SSR though? I think this is mostly used in demo pages and *maybe* tests (although less common there).

**Comment by justinbmeyer** [comment]
What's the use case for using a selector instead of an ID?  I can't remember a selector ever being used.

**Comment by matthewp** [comment]
There's probably not a great one, maybe if you wanted to avoid adding an id and use `[type=text/stache]` instead.

Btw, the browser already sets all IDs as globals so it would be great if this API could take in an Element as well:

```html
<script type="text/stache" id="myTemplate">
  {{name}}
</script>
<script src="steal.js">
  var stache = require("can-stache");

  var render = stache.from(myTemplate);
</script>
```
