### ISSUE TITLE
Stache is not invoking functions when passed as an argument to a helper expression

### ISSUE THREAD

**Issue by michaelzcheng** [canjs/can-stache#573]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
It seems that stache is not executing function invocations when in a helper expression

```js
import { stache } from "//unpkg.com/can@5/core.mjs";

stache.registerHelper("helper", (arg) => {
  console.log("Helper was called with arg", arg);
  return arg;
});

const template = `
  <h2>helper some.key</h2>
  <p>  
    {{ helper some.key() }}
  </p>

  <h2>some.key</h2>
  <p>
    {{ some.key() }}
  </p>
`;

const data = {
  some: {
    key:() => "a string"
  }
};

document.body.appendChild(
  stache(template)(data)
);
```

will print:
`<h2>helper some.key</h2>
  <p>  
 
  </p>

  <h2>some.key</h2>
  <p>
    a string
  </p>
`

See the codepen below:
https://codepen.io/MichaelZC/pen/RBLboP?editors=0011

**Comment by matthewp** [comment]
Is the 4.0 label accurate here?

**Comment by michaelzcheng** [comment]
It's not. Sorry.

**Comment by phillipskevin** [comment]
Very confusing, but canjs 5.0 is using stache 4.0.

**Comment by matthewp** [comment]
Oh :D

**Comment by cherifGsoul** [comment]
```addHelper``` works as expected https://codepen.io/cherifGsoul/pen/robJRq?editors=0011

**Comment by cherifGsoul** [comment]
This will work with `addHelper`, because `addhelper` passes compute and the function will be invoked, which is not the case with `registerHelper`, so if you want the function to get invoked just use `addHelper` or invoke the function inside the helper like the following:
```js
stache.registerHelper("helper", (arg) => {
  return arg();
});
```
