### ISSUE TITLE
Proposal: Support CanJS 3.0 scope walking via special syntax

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#586]
In 3.0, key lookup would walk the scope.  For example, the following `{{user.name}}` will be able to find a `user` object on the outer view-model:

```
{{#each user.addresses}}
  {{user.name}}  {{street}}
{{/each}}
```

In 4.0, (until #528) this needs to be written like:

```
{{#each user.addresses}}
  {{../user.name}}  {{street}}
{{/each}}
```

Making these changes can make the upgrade process a bit annoying (even if CanJS 3.0 will warn you about where to make these changes).

Currently, one can get scope walking using `scope.find()` like:

```
{{#each user.addresses}}
  {{scope.find("user.name")}}  {{street}}
{{/each}}
```

But that's a lot and no one will upgrade to using `scope.find`.

So we'd like to add some shorthand to enable scope walking.  Ideally, these shorthands would:

- Fit in with `./` and `../` which are already used to signal scope walking.
- Not add additional special characters so we can reserve them for other uses.

Currently, the following satisfies these conditions:

- `{{scope/key}}`

These would result in:

```
{{#each user.addresses}}
  {{scope/user.name}}  {{street}}
{{/each}}
```

Other possibilities:

- `{{//key}}` - It doesn't add special characters, but it could be tricky to disambiguate `{{/foo}}` from `{{//foo}}`.
- `{{?/key}}`
- `{{*/key}}`

## Examples

```
{{ scope/method( scope/key ) }}
```

**Comment by bmomberger-bitovi** [comment]
I like `{{*/key}}` because it looks like a glob or Kleene closure.

**Comment by bmomberger-bitovi** [comment]
BTW, scope walking is more than just an upgrade issue. Partials are cumbersome to use without it.

If I may make a suggestion, let's also consider a "turn scope walking on for this script or section" operator, like the use of `(?` for enabling flags in regexes.

Not sure what the best syntax would be, but as an example, `{{?: walkScope}}` at the top level could just turn on scope walking for a script.  This would be contextual, so `{{<p}}{{?: walkScope}} {{foo}}{{/p}} {{>p}} {{bar}}` would walk the scope for `foo` but not `bar`.

**Comment by justinbmeyer** [comment]
Why are partials hard to use? You can pass values to a partial.

**Comment by bmomberger-bitovi** [comment]
That's not what I said.

Partials *without scope walking* are *cumbersome* and *having to pass values is the reason why.*

**Comment by justinbmeyer** [comment]
@bmomberger-bitovi can you give an example of where passing is cumbersome?  Are you often having to pass many values?

**Comment by justinbmeyer** [comment]
To implement this, one probably needs to make 2 changes.  Somewhere in here:

https://github.com/canjs/can-view-scope/blob/7a17b8ea6c85a0ecbdb06d3384619523d820c55f/can-view-scope.js#L98

We'd identify if the `attr` started with `scope/`.  For `"scope/foo"`, we'd return something like:

```js
{walkScope: true, remainingKey: "foo"}
```

Then we'd need to add another case to this set of `if/if else`s: https://github.com/canjs/can-view-scope/blob/7a17b8ea6c85a0ecbdb06d3384619523d820c55f/can-view-scope.js#L306

```js
}
else if(keyInfo.walkScope){
 SETUP_RULES_FOR_THIS_SCOPE_WALKING
}
```

**Comment by matthewp** [comment]
Reopening for docs.
