### ISSUE TITLE
Move the `not` converter into stache

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#599]
I'm beginning to dislike `{{^}}`.  If we can't use `{{!}}` as it is reserved for comments, I'd like to at least have access to the `not()` helper in core so I could write:

```
{{# if( not( value ) ) }} .... {{/ if }}
```

instead of:

```
{{^ if( value ) }} .... {{/ if }}
```

can-stache-converters has a `not` helper already. We'd just have to move that into `can-stache`.

**Comment by Mattchewone** [comment]
Would the `not` helper be moved and removed from `can-stache-converters`? or would it be copied and kept in the helpers still?

**Comment by matthewp** [comment]
I will stay there for backwards compat.

**Comment by justinbmeyer** [comment]
I moved it and changed `can-stache-converters` to check if `not` exists and only add it if it does not.
