### ISSUE TITLE
Support whitespace control

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#60]
From: https://github.com/canjs/canjs/issues/2284

If not yet supported, please support whitespace control like Handlebars: http://handlebarsjs.com/expressions.html#whitespace-control

My use case: `:empty` pseudo selector, which does not match

```
<div> </div>

<div>
  <!-- test -->
</div>

<div>
</div>
```

Background:
- https://css-tricks.com/almanac/selectors/e/empty/
- http://thenewcode.com/692/Vanishing-Acts-The-CSS-empty-Selector
- http://codepen.io/katydecorah/post/a-case-for-empty
- https://stackoverflow.com/questions/15953293/handlebars-whitespace-control ⇒ https://github.com/wycats/handlebars.js/pull/336

**Comment by justinbmeyer** [comment]
This would have to use some other syntax.  `~` is reserved for computes.

**Comment by justinbmeyer** [comment]
Thumbs up if people would like us to prioritize!

**Comment by DrecDroid** [comment]
Jinja solves this adding a minus sign after the opening braces or before the closing braces to remove the whitespace before or after the content.
http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

**Comment by Schweinepriester** [comment]
As <https://github.com/canjs/can-stache/releases/tag/v3.3.0> is out, this probably can be closed? :)
