### ISSUE TITLE
stache.safeString renders as [object Object]

### ISSUE THREAD

**Issue by eben-roux** [canjs/can-stache#603]
When using `stache.safeString` the version I was using returned an object with a `toString()` method.  The latest returns `{Symbol(can.toDOM): ƒ}` and renders as `[object Object]`.  

Using Justin's codepen as a basis I created [this one](https://codepen.io/eben-roux/pen/dgNPEY).

**Comment by justinbmeyer** [comment]
Discussion: https://gitter.im/canjs/canjs?at=5bbba1c0ef4afc4f283c2fb3
