### ISSUE TITLE
Allow partials to be passed data

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#611]
Partials should be able to be passed data.  For example:

```
{{< address}}
  <label>{{street}}, {{city}}</label>
{{/ address}}

{{>address street=user1.streetName city=user1.location}}
```

I'm not sure what the nature of this should be.  I see two options:

- pass as a new normal context.
- pass as a `LetContext`.

before deciding, some background:

## Background 

Currently, partials render with the context at the call site. For example, the following will log `{name: "Justin"}`:

```js
var addressView = stache(`{{ console.log(this) }}`)

var view = stache(`
  {{# person }}
    {{>../addressView }}
  {{/ person}}
`)({
  person: {name: "Justin"},
  addressView: addressView
});
```

Also, partials can be passed an object that gets added to the scope.  The following logs `{name: "Fido"}, {name: "Justin"}`:

```js
var addressView = stache(`{{ console.log(this, ../ ) }}`)

var view = stache(`
  {{# person }}
    {{>../addressView ../dog}}
  {{/ person}}
`)({
  person: {name: "Justin"},
  dog: {name: "Fido"},
  addressView: addressView
});
```

Curiously, partials will also have access to any let variables.  The following will log `Justin`:

```js
var addressView = stache(`{{ console.log(name) }}`)

var view = stache(`
  {{let name=person.name}}
  {{>addressView }}
`)({
  person: {name: "Justin"},
  addressView: addressView
});
```

## Pass as a new normal context 

If passing as a normal context, then one would probably want to write this as:

```
{{< address}}
  <label>{{this.street}}, {{this.city}}</label>
{{/ address}}

{{>address street=user1.streetName city=user1.location}}
```

All of the same rules would apply above.

## Pass as a `LetContext`

If passing as a `LetContext`, this allows us to treat partials as more simple functions:

```
{{< address}}
  <label>{{street}}, {{city}}</label>
{{/ address}}

{{>address street=this.user1.streetName city=this.user1.location}}
```

But this brings up a few other questions:

#### Q1: What should the `this`/context be in this case?  

In the case of an inline partial, I see a strong case that `this` should be the `ViewModel`:

```
{{< address}}
  <label>{{ this.someMethod( street ) }}, {{city}}</label>
{{/ address}}

{{>address street=this.user1.streetName city=this.user1.location}}
```

But for external partials, having access to a `this` doesn't make sense and should probably be undefined.

#### Q2: Should we allow passing the scope or a context?

We could pass a context like:

```html
{{< address}}
  <label>{{ this.someMethod( street ) }}, {{city}}</label>
{{/ address}}

{{>address this street=this.user1.streetName city=this.user1.location}}
```

Or an entire scope like:

```html
{{< address}}
  <label>{{ this.someMethod( street ) }}, {{city}}</label>
{{/ address}}

{{>address scope street=this.user1.streetName city=this.user1.location}}
```

#### Q3: Should the partial have access to variables?

What should `console.log` print?  Should `myVariable` or the current `user` be available?

```html
{{ let myVariable="something" }}

{{< address}}
  {{ console.log(myVariable, user, street, city )
{{/ address}}

{{# for(user of users) }}
  {{>address street=user.streetName city=user.location}}
{{/ for }}
```

**Comment by justinbmeyer** [comment]
My thoughts:

I think we should treat inline partials as close to how arrow JavaScript functions would behave.  

__Q1: What should the this/context be in this case?__

This means that calling them like `{{>somePartial a="b"}}` is the same as `somePartial( {a: "b"} )`.  

I see the following as roughly the same:

```js
view(){
  var somePartial = ( {a} )=> {
    console.log(this, a)
  }
  somePartial({a: "b"})
}
```

```html
{{<somePartial}}
  {{ console.log(this, a) }}
{{/somePartial}}

{{>somePartial a="b"}}
```

And it would maintain the current context, so `this` would be the `ViewModel` for inline partials.  

Partials created like the following would have `this` be undefined:

```js
var somePartial = stache(`{{ console.log(this) }}`)

var view = stache(`
    {{>somePartial a='b' }}
`)({
  somePartial: somePartial
});
```

__Q2: Should we allow passing the scope or a context?__

Yes


__Q3: Should the partial have access to variables?__

Only the template level variables as JS functions would have access to things in their scope too.

**Comment by frank-dspeed** [comment]
@justinbmeyer little question what do you think is the advanced of a partial over a normal stache rendered section ?

i think this partials in general would not be needed because we can register and return any stache via call expressions inside the stache templates that results out of my view in a partial where i can supply scope or context or even live bind that via simply giving it from the calling viewModel the this.property computes.

**Comment by justinbmeyer** [comment]
@frank-dspeed Can you give an example of what you are talking about?  My guess is that what you are doing might need to be done carefully to make sure nodelists are working right.

**Comment by matthewp** [comment]
Sounds good to me. Agree that an inline partial's `this` should always refer to the template's VM. Arrow function is a good analogy there.

**Comment by justinbmeyer** [comment]
In the future, I would suggest we make the following breaking changes:

`{{>somePartial}}` Should render a partial with effectively an empty scope.

`{{>somePartial context}}` Should render a partial with that context, but only that context is in the scope.

For backward compat, people can do:


```
{{>somePartial scope}}
```

```
{{>somePartial scope.add(context) }}
```

**Comment by justinbmeyer** [comment]
## Other Thoughts

- It might be possible to make `{{>}}` use call expressions and show that `{{>somePartial()}}` -> no arguments.
   - Should this be the same as `{{somePartial()}}`?
   - `{{ somePartial(a="b") }}` will make a new context.
   - `{{> somePartial( a="b" ) }}` should make a let context
   -  `{{ somePartial.call(context, scope.let(a="b") ) }}`
  



- Partials should be available as variables?  They are statically defined.


## The Plan

1.  Add hash expressions (no breaking change)
	WHY: So avoid teaching people about ../. just to use partials 

2.  Breaking changes 
	{{>foo.call(this, foo=bar)}} -> {{>foo scope}}
	WHY: Uniform behavior 
	

	
	{{>view(foo="bar")}} -> view( new LetContext({foo: "bar"}) )
	{{view(foo=bar)}} -> view({foo:"bar"})

**Comment by frank-dspeed** [comment]
@justinbmeyer https://codepen.io/frank-dspeed/pen/KGemLG

example that shows what i mean it is also related to https://github.com/canjs/canjs/issues/4517

**Comment by chasenlehara** [comment]
Partial syntax is deprecated, so closing this issue.

**Comment by frank-dspeed** [comment]
this is also related to https://github.com/canjs/canjs/issues/3864 for creating animated partials its the same
