### ISSUE TITLE
In a #each, stache thinks {{0}} is looking for a helper and then throws an error.

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-stache#615]
This is the example stache:

```handlebars
{{#each(options)}}
  <div class="item" data-value="{{1}}">{{0}}</div>
{{/each}}
```
`options` is defined as:

```js
const options = new DefineList([
  new DefineMap({ "0": 'Hello', "1": 'World' })
]);
```

The warning and error on the console will look like:

<img width="728" alt="screen shot 2018-10-22 at 5 09 28 pm" src="https://user-images.githubusercontent.com/212726/47320808-81d02700-d620-11e8-94a2-510353a6bb09.png">

This error can be prevented by two means:

The use of `this`
```handlebars
{{#each(options)}}
  <div class="item" data-value="{{this.1}}">{{this.0}}</div>
{{/each}}
```

Use stache's `for` expression
```handlebars
{{#for(option of options)}}
  <div class="item" data-value="{{option.1}}">{{option.0}}</div>
{{/for}}
```

**Comment by Mattchewone** [comment]
Seems to be two issues here I think:
```js
{{#each(options)}}
  <div class="item">{{0}}</div>
{{/each}}
```
Will render with a warning, but won't throw. The error seems to be from the attribute observable on `data-value="{{1}}"`

**Comment by chasenlehara** [comment]
@Mattchewone Was this fixed?
