### ISSUE TITLE
Addition property access with [] operator fails in call expression

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-stache#620]
can-stache: v4.14.1

```js
const thing = {
  property: [1, 2, 3, 4]
}
```

```handlebars
{{console.log(thing['property'][0])}}
```
fails and will not print `1` to the console BUT will render it to the DOM

This can be worked around by using `.` to access the property

```handlebars
{{console.log(thing['property'].0)}}
```

**Comment by phillipskevin** [comment]
I think parsing is just broken in this case. It is parsing it as if the `console.log(  )` isn't there:

![image](https://user-images.githubusercontent.com/5851984/48155088-d4038000-e28f-11e8-81b2-b9c58fe94a57.png)
