### ISSUE TITLE
Lack of warning and unexpected value from prop={{#if()}}"value0"{{else}}"value1"{{/if}}

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-stache#630]
Given the following binding:

`childProperty:raw={{#if(isSomething)}}"something"{{else}}"something else"{{/if}}`

In the DOM the binding is rendered as follows:

`child:u:property:raw=""something""`

On the child component `childProperty` is defined as `type: 'string'`. The value of `childProperty` is  `''` (empty-string).

I was informed that this syntax is not supported by stache, but there is also no warning or error on the console.

If this is not valid syntax, we should inform the developer with a warning or an error.

**Comment by justinbmeyer** [comment]
This probably needs to be fixed in can-view-parser

**Comment by cherifGsoul** [comment]
Should this issue be moved to `can-view-parser` ?
