### ISSUE TITLE
Misleading error message if {{#let ...}} is used without closing tag

### ISSUE THREAD

**Issue by James0x57** [canjs/can-stache#675]
I was trying to pass variables between components without cluttering the vm:
```html
{{#let bob=undefined}}
<my-component hasItem:to="bob" />

<div class="main-body">
  <other-component wantsItem:from="bob" />
</div>
```
I could not figure out what I was doing wrong partially because this was the error message:
![image](https://user-images.githubusercontent.com/7545075/55223583-822aaa80-51dc-11e9-919d-e50ee37c3ce2.png)
This is the same error you'd get without using let if `bob` wasn't on the VM.

The actual problem is that the `let` I'm using is for defining it within its own block and has no close tag so the let var doesn't get added to the scope. That should maybe cause its own error?

It works fine if I remove the `#` or close the block, of course, but as someone new to the `let` expressions I didn't realize it until some time later what I did wrong. I just put `bob` on the VM and avoided `let` at the time.

Thank you for your time,
🍻

**Comment by cherifGsoul** [comment]
@James0x57 I can not reproduce the issue in this [CodePen](https://codepen.io/cherifGsoul/pen/EJyyBO) , can you please provide more information on how to reproduce the issue or correct my CodePen.

**Comment by cherifGsoul** [comment]
But the following case throws a warning:
```html
{{#let bar="Bar"}}
  <child-com foo:from="bar"></child-com>
```
`Unable to find key "bar".`

**Comment by cherifGsoul** [comment]
`{{# let }} ...` doesn't run  when the closing tag is missed

**Comment by James0x57** [comment]
https://codepen.io/anon/pen/BEQmoG
per convo in the bitovi community slack ^ 
Sorry I didn't see these responses sooner!
