### ISSUE TITLE
Replace can-view-nodelist

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#679]
[can-view-nodelist](https://github.com/canjs/can-view-nodelist) has long been a maintenance burden and a source of bugs. This Epic is to replace the current version of `can-view-nodelist` that meets these goals:

1. Invisible to users
2. Maintainable
3. Isolated (no global state)
4. Performant

It might not be possible to meet all of these goals.

**Comment by phillipskevin** [comment]
Here is a proposal for a new API for `can-view-nodelist`: https://github.com/canjs/can-view-nodelist/issues/37.

**Comment by phillipskevin** [comment]
Here is a proposal to use Comment Nodes to store the "depth" of elements/sections using live binding so that event listeners can be torn down in the correct order: https://github.com/canjs/can-stache/issues/680.

**Comment by chasenlehara** [comment]
Is it known that there are still references to nodelists in the 6.x codebase?

- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/can-stache.js#L245
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/can-stache.js#L314
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/can-stache.js#L380
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/can-stache.js#L500
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/src/utils.js#L85
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/helpers/core.js#L402
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/test/test.js#L2
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/expressions/call.js#L99
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/test/stache-test.js#L3353
- https://github.com/canjs/can-stache/blob/1c3b35f3b9a18c106bbbe47d792a0616c749b08b/docs/view.md

**Comment by phillipskevin** [comment]
I knew some of these still existed in the code (the one in the docs looks like it was just missed). Since `can-view-nodelist` is not included in core, these can be cleaned up whenever. Whoever updates the `can-stache` docs for https://github.com/canjs/canjs/issues/5119 can clean these up also.

**Comment by phillipskevin** [comment]
cc @matthewp

**Comment by matthewp** [comment]
Closed by #720
