### ISSUE TITLE
#each isIterable case not being hit

### ISSUE THREAD

**Issue by garrettreed** [canjs/can-stache#68]
[The `isIterable` case within the each helper](https://github.com/canjs/can-stache/blob/master/helpers/core.js#L114) is not being hit by any of the current tests. That scenario would cause `isIterable` to be true within this helper?

@justinbmeyer brought this while working on #62. We expected a can.Map to match this case.

**Comment by matthewp** [comment]
can-maps are not iterable currently. They would have to implement the iterable API like can-define does here: https://github.com/canjs/can-define/blob/master/can-define.js#L107-L109

**Comment by christopherjbaker** [comment]
Solved by canjs/can-define#167, but pending canjs/can-reflect#1

**Comment by matthewp** [comment]
@christopherjbaker I think we need the same thing in can-map.

**Comment by christopherjbaker** [comment]
Hmm. Adding it the same way to can-map would add a dependency to can-define, which seems counter-productive. I was going to implement it as-is now, but I think its better to wait for can-reflect.

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-map #67](https://github.com/canjs/can-map/issues/67) via [**ZenHub**](https://www.zenhub.com/)

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-map #66](https://github.com/canjs/can-map/issues/66) via [**ZenHub**](https://www.zenhub.com/)
