### ISSUE TITLE
Add inverse expression to support falsy values

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-stache#681]
Currently inverse expressions is not supported
Given this example with simple setter stache binding:
`<button on:click="this.isOpen = !isOpen">Toggle</button>`

I'm not sure if we should add another expression type `Inverse` or just support this in `Lookup` type?

Related https://github.com/canjs/can-stache-bindings/issues/516

**Comment by phillipskevin** [comment]
You can do `on:click="this.isOpen = not(isOpen)"`. I think this is still nice, but maybe not super important.

**Comment by phillipskevin** [comment]
And we should document using the [not converter](https://canjs.com/doc/can-stache-converters.not.html) like this if it's not documented.
