### ISSUE TITLE
Bracket expression with undefined value throws an error

### ISSUE THREAD

**Issue by ccummings** [canjs/can-stache#91]
If you have a template like:

```html
<h1>{{place['place:name']}}</h1>
```

And `place` is undefined, an error `options.get is not a function` is thrown in [helpers/core.js](https://github.com/canjs/can-stache/blob/master/helpers/core.js#L316).

With non-bracket syntax this sort of thing is fine:

```html
<h1>{{place.placeName}}</h1>
```

This is the same error I got when using colons in stache before switching to brackets (`{{place.place:name}}`.

**Comment by phillipskevin** [comment]
@ccummings can-stache@3.0.3 is published with this change.
